### ISSUE TITLE
getDocumentPositionGrossPriceAllowanceCharge -> error "Undefined offset: 0"

### ISSUE THREAD

**Issue by rycks** [horstoeko/zugferd#1]
Hello,
each time i use that function getDocumentPositionGrossPriceAllowanceCharge to get discount % rate i get this error : "Undefined offset: 0"

Error on vendor/horstoeko/zugferd/src/ZugferdDocumentReader.php, line 3341

What could i do to fix that ?

Thanks

**Comment by rycks** [comment]
Hello again,
that was due to an bad factur-x invoice ... but i think we could add some barrier against that sort of problem ?

i think i could add some `if(isset($array[$access]))` in your code if you validate that idea ?

Éric

**Comment by horstoeko** [comment]
Hi @rycks,

thank you four your issue. I will have a look at it. Can you send me the "wrong" invoice?

**Comment by horstoeko** [comment]
Hi @rycks 

Thank you very much for your mail with the sample invoice. I was able to read your invoice without any problems. I guess that you called the `getDocumentPositionGrossPriceAllowanceCharge` method directly without calling the `firstDocumentPositionGrossPriceAllowanceCharge `method first. The latter returns a True if there is at least one discount/allowance item for the gross price. However, I agree with you that you should at least throw an error there if the method is called directly and no discount/surcharge item is present. Please let me know if I have understood and reproduced this correctly. If yes, then I will implement an appropriate check at this (and also at some similar places).

**Comment by rycks** [comment]
Hmmmmm @horstoeko,
you understood exactly the problem !
And thanks again for pointing me on firstDocumentPositionGrossPriceAllowanceCharge function, yes i forget to use it and now there is no more problem with that sort of invoices !

**Comment by horstoeko** [comment]
@rycks 

This sounds great. There are other first/next methods at the position level, such as `firstDocumentPositionNote`, `firstDocumentPositionAdditionalReferencedDocument`, `firstDocumentPositionGrossPriceAllowanceCharge`, `firstDocumentPositionTax `and `firstDocumentPositionAllowanceCharge`.

Admittedly, I should probably improve the documentation a bit. :-)
