### ISSUE TITLE
Fully payed invoices aren't valid

### ISSUE THREAD

**Issue by LarsK1** [horstoeko/zugferd#10]
Hi,
when generating an already payed invoice using XRechnung_2.2, the generated xml is invalid. See the examples afterwards:

**payed:**
```
<ram:SpecifiedTradeSettlementHeaderMonetarySummation>
<ram:LineTotalAmount>34.60</ram:LineTotalAmount>
<ram:ChargeTotalAmount>0.00</ram:ChargeTotalAmount>
<ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
<ram:TaxBasisTotalAmount>34.60</ram:TaxBasisTotalAmount>
<ram:TaxTotalAmount currencyID="EUR">6.57</ram:TaxTotalAmount>
<ram:GrandTotalAmount>41.17</ram:GrandTotalAmount>
<ram:DuePayableAmount>0.00</ram:DuePayableAmount>
</ram:SpecifiedTradeSettlementHeaderMonetarySummation>
</ram:ApplicableHeaderTradeSettlement>
```

**unpayed:**
```
<ram:SpecifiedTradeSettlementHeaderMonetarySummation>
<ram:LineTotalAmount>403.61</ram:LineTotalAmount>
<ram:ChargeTotalAmount>0.00</ram:ChargeTotalAmount>
<ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
<ram:TaxBasisTotalAmount>403.61</ram:TaxBasisTotalAmount>
<ram:TaxTotalAmount currencyID="EUR">76.69</ram:TaxTotalAmount>
<ram:GrandTotalAmount>480.30</ram:GrandTotalAmount>

THE FOLLOWING LINE IS MISSING IN THE PAYED XML
<ram:TotalPrepaidAmount>0.00</ram:TotalPrepaidAmount>
-----------------------------------------
<ram:DuePayableAmount>480.30</ram:DuePayableAmount>
</ram:SpecifiedTradeSettlementHeaderMonetarySummation>
</ram:ApplicableHeaderTradeSettlement>
```

If you need anything else let me know.
Lars

**Comment by horstoeko** [comment]
Hi  @LarsK1,

can you send me a little snippet of the code which you use?

**Comment by LarsK1** [comment]
Hi @horstoeko,
your code is issued in an invoicing system. See here: https://github.com/invoiceninja/invoiceninja/blob/557db4ce5e82ba3a4111f7cfc802d1be21601ada/app/Services/Invoice/EInvoice/ZugferdEInvoice.php#L166

**Comment by LarsK1** [comment]
Hi,
I just had a look. If the invoice is fully paid, the condition isPartial() is met. The field then return the string "0.0000". I just changed it to a float with the value 0.0. The issue still exists...

```
        if ($this->invoice->isPartial()) {
            $xrechnung->setDocumentSummation($this->invoice->amount, $this->invoice->balance, $invoicing_data->getSubTotal(), $invoicing_data->getTotalSurcharges(), $invoicing_data->getTotalDiscount(), $invoicing_data->getSubTotal(), $invoicing_data->getItemTotalTaxes(), null, 0.0);
        } else {
            $xrechnung->setDocumentSummation($this->invoice->amount, $this->invoice->balance, $invoicing_data->getSubTotal(), $invoicing_data->getTotalSurcharges(), $invoicing_data->getTotalDiscount(), $invoicing_data->getSubTotal(), $invoicing_data->getItemTotalTaxes(), null, 0.0);
        }
```
![image](https://github.com/horstoeko/zugferd/assets/28981528/b7b8c6a8-7fe3-4b5e-91fd-6994022aef3e)
I've attached the xml-invoice for test again (please rename the file extension to .xml)
[Rechnung.txt](https://github.com/horstoeko/zugferd/files/11939783/Rechnung.txt)

**Comment by horstoeko** [comment]
Hi @LarsK1,

i don't think this is a library problem. My implementation does not calculate amounts automatically. So you have to set the DuePayableAmount yourself. But it could be that I still don't understand your problem ;-). In your example the DuePayableAmount should be 59.50 according to my understanding.

**Comment by LarsK1** [comment]
Hi @horstoeko ,
I've just got an idea: how can I set the payed amount?

**Comment by horstoeko** [comment]
Hi @LarsK1,

The amount already paid can be set via the last parameter of the ``setDocumentSummation`` method. See:

```php
public function setDocumentSummation(
  float $grandTotalAmount,
  float $duePayableAmount,
  ?float $lineTotalAmount = null,
  ?float $chargeTotalAmount = null,
  ?float $allowanceTotalAmount = null,
  ?float $taxBasisTotalAmount = null,
  ?float $taxTotalAmount = null,
  ?float $roundingAmount = null,
  ?float $totalPrepaidAmount = null): ZugferdDocumentBuilder
```

I hope this helps you. In any case, please keep me informed.

**Comment by LarsK1** [comment]
Hi @horstoeko ,
can we check together, that I understand the command the right way? Take an example invoice of 100 € net and 119 € grand total.

Unpayed:
`setDocumentSummation(119.0, 119.0, 100.0, 0.0, 0.0, 100.0, 119.0, 0.0, 0.0)`

Partially payed (80€ payed):
`setDocumentSummation(119.0, 39.0, 100.0, 0.0, 0.0, 100.0, 119.0, 0.0, 80.0)`

fully payed:
`setDocumentSummation(119.0, 0.0, 100.0, 0.0, 0.0, 100.0, 119.0, 0.0, 119.0)`

Thank you for your help in advance!
Lars

**Comment by LarsK1** [comment]
Hi @horstoeko ,
understood. Thanks for your help. I fixed my implemtation - I totally misunderstood the last and second parameter.
Now it works as expected.
