### ISSUE TITLE
[QUESTION] setDocumentShipToAddress() adds no shipping data

### ISSUE THREAD

**Issue by SM-WEKANDO** [horstoeko/zugferd#101]
I need to add shipping data for an intra-community supply. The function setDocumentShipToAddress() doesn't add the shipment data to the resulting invoice. Other shipment data functions also do not add shipment data ..

I use XRECHNUNG_3 profile, the invoice contains one item (83.98€) with no tax and a rebate of 10%. The official validator reports a single error for the shipment country when using intra-community supply. All other data semm to be correct.

I expect that setDocumentShipToAddress() adds the shipment data to resolve the problem.

This is the result of the verification with the validator.
![grafik](https://github.com/user-attachments/assets/d2bc8296-1f67-4bcf-aaa5-4303a23e0bab)

**Additional information:**
 - Windows 11 with xampp
 - PHP8.1

**Comment by horstoeko** [comment]
Hi @SM-WEKANDO,

Unfortunately, I can't understand your problem. Your error report (see screenshot) has nothing to do with a delivery address. The error log only says that you have an invalid tax category ("Intra-...."). This does not exist. Unfortunately, I cannot make the connection to your problem with any delivery data. Please give me some clarity.

**Comment by SM-WEKANDO** [comment]
Hello [horstoeko](https://github.com/horstoeko),

I don't think so. The error code BR-IC-12 says that the country code (BT-80) must be set when using intracommunity delivery in BT-118. I want to try to set it but the function setDocumentShipToAddress() that sets BT-80 with its 6th argument doesn't add any data to the resulting xml.

**Comment by horstoeko** [comment]
Hello @SM-WEKANDO ,

Unfortunately, I can't understand it all. The unit tests that test exactly this method are "green". Can you please provide me with your code? Please also check again whether you are really passing a non-empty value for the country.

**Comment by SM-WEKANDO** [comment]
Thank you [horstoeko](https://github.com/horstoeko),

it took me a while to create an example for a review. In the meantime you solved the problem - it was the missing call to setDocumentShipTo().

I apologize for any inconvience and thanks for your good work at all. :)

**Comment by horstoeko** [comment]
Hi @SM-WEKANDO, 

> it took me a while to create an example for a review. In the meantime you solved the problem - it was the missing call to setDocumentShipTo().
> I apologize for any inconvience and thanks for your good work at all. :)

Nice that the problem has been solved. Continue to enjoy the library. And you don't have to apologize - we're all only human... :-)
