### ISSUE TITLE
[BUG] PDF Merger / Loose Comparison / adherence to PDF/A-3b / EOL marker shall be immediately followed by a %

### ISSUE THREAD

**Issue by crocodileneptune** [horstoeko/zugferd#103]
**Describe the bug**
I was following the example code as it is provided in the file En16931PdfMerger.php. The VeraPDF validator https://demo.verapdf.org/ shows a failure when validating a Zugferd PDF using the PDF/A-3b profile: 

> The aforementioned EOL marker shall be immediately followed by a % (25h) character followed by at least four bytes, each of whose encoded byte values shall have a decimal value greater than 127
 

**To Reproduce**
The error message pointed me to other code https://www.minka.gob.ec/Ramirofl/odoo/-/blob/15.0/odoo/tools/pdf.py which put the spotlight on the PDF version header (`self._header = b"%PDF-1.7\n%\xFF\xFF\xFF\xFF"`). The file ZugferdPdfWriter.php seems to be prepared to output the relevant characters (lines 96-102) below
```
    public function setPdfVersion($version = '1.3', $binary_data = false): void
    {
        $this->PDFVersion = sprintf('%.1F', $version);
        if (true == $binary_data) {
            $this->PDFVersion .=
                "\n" . '%' .
                chr(rand(128, 256)) .
                chr(rand(128, 256)) .
                chr(rand(128, 256)) .
                chr(rand(128, 256));
        }
    } 
```
and seems to be called appropriately from the file ZugferdDocumentPdfBuilderAbstract.php
`$this->pdfWriter->setPdfVersion('1.7', true);` However, the loose comparison in line 95 seems to be the issue.

**Proposed Resolution**
Once I enforce strict comparison (as shown in the line below), the resulting Zugferd PDF is validated successfully.
`if (true === $binary_data) {`

**Additional information:**
 - OS: Linux
 - OS-Version: Debian 11 Bullseye
 - PHP-Version PHP 7.4

**Comment by horstoeko** [comment]
Hi @crocodileneptune ,

thanks for your issue, but unfortunately I can't find any errors. Even without the strict check of the IF branch you mentioned, it is entered correctly. I have just debugged it manually just to be on the safe side. Unfortunately, I am now at a loss as to how I can help you. The official validators of the community have not found any errors in the PDFs I created.

Best regards
