### ISSUE TITLE
[BUG] By reading an XML that is not a X-Rechnung a warning is emitted

### ISSUE THREAD

**Issue by oschildt** [horstoeko/zugferd#104]
**Describe the bug**
By reading an XML that is not a X-Rechnung with ZugferdDocumentReader::readAndGuessFromFile, a programming warning is emitted.

Warning: SimpleXMLElement::xpath(): Undefined namespace prefix in C:\work\pdf\vendor\horstoeko\zugferd\src\ZugferdProfileResolver.php on line 38

**To Reproduce**
Use any XML that is not a X-Rechnung.

**Expected behavior**
The call should return null without any warning as it is done if a non-zugferd pdf is being read and no warnings should occur.

**Sample Code**
try
{
  $document = ZugferdDocumentReader::readAndGuessFromFile(dirname(__FILE__) . "/reservation-2.request.xml");
}
catch(Throwable $ex)
{
}

$is_valid = false;

if (!empty($document))
{
  $xsdValidator = new ZugferdXsdValidator($document);
  $xsdValidator->validate();

  $is_valid = $xsdValidator->validationPased();
}

**Additional information:**
 - OS: Windows
 - OS-Version: Windwos 11
 - PHP-Version: 8.3.1

**Comment by horstoeko** [comment]
Hi  @oschildt,

First of all, thank you for your contribution. With the next release, an exception of the class ZugferdUnknownXmlContentException will be raised if the XML content is inappropriate.

Best regards

**Comment by oschildt** [comment]
Hi,

thank you for quick response. Your library is a great work! I appreciate it very much!

Please consider also a case if the XML structure is invalid. In that case also, just an exception should occur instead on programming warnings.

Warning: SimpleXMLElement::__construct(): Entity: line 146: parser error : Opening and ending tag mismatch: OTA4_HotelResNotifRQ line 2 and OTA_HotelResNotifRQ in C:\work\pdf\vendor\horstoeko\zugferd\src\ZugferdProfileResolver.php on line 37

Warning: SimpleXMLElement::__construct(): </OTA_HotelResNotifRQ> in C:\work\pdf\vendor\horstoeko\zugferd\src\ZugferdProfileResolver.php on line 37

Warning: SimpleXMLElement::__construct(): ^ in C:\work\pdf\vendor\horstoeko\zugferd\src\ZugferdProfileResolver.php on line 37

**Comment by horstoeko** [comment]
Hi @oschildt ,

> thank you for quick response. Your library is a great work! I appreciate it very much!

Thank you very much for the kind words - I really appreciate it.

> Please consider also a case if the XML structure is invalid. In that case also, just an exception should occur instead on programming warnings.

I will try to solve this more elegantly today. I already have an idea. 

Best regards

**Comment by horstoeko** [comment]
Hi @oschildt,

Hopefully I have now found a more elegant solution to your problem and would be pleased if you would take a look at the changes and give me feedback. See the changes in [ZugferdProfileResolver.php](https://github.com/horstoeko/zugferd/commit/c05d6d43d9779613fa5d7dbc445b7426c3691b98#diff-130c8b99f799b4d4c7add8cbc0ed5c5e4c7ad9b99a9f2d64f53e527c9fa3873e)

Many thanks and best regards

**Comment by oschildt** [comment]
Hi,

I have tested it. The solution is good and robust. It works fine.

**Comment by horstoeko** [comment]
Hi @oschildt,

Thank you very much for your feedback. I will make a new release and close the issue.

Kind regards
