### ISSUE TITLE
[QUESTION] problem validating default example writing a pdf file with attached xml file

### ISSUE THREAD

**Issue by Flaschenzug** [horstoeko/zugferd#111]
**Your question**
I just started to use zugferd to add xml to bills.
Everything works as expected if I use the example from here: https://github.com/horstoeko/zugferd?tab=readme-ov-file#writing-a-pdf-file-with-attached-xml-file

But If I try to validate the data using this tool: https://validator.invoice-portal.de/
I get the following errors:

> general information: XSD Schema: CrossIndustryInvoice (2 errors)
> 1. error: Fatal 4 at line 1 > Start tag expected, '<' not found
> 2. error: Error 1872 at line -1 > The document has no document element.

Can anyone confirm that this is really happening using the default code?
And if so: Any ideas why and how to solve it?

Thanks :-)

**Comment by chris-sx** [comment]
You can tryCreateNew(ZugferdProfiles::PROFILE_XRECHNUNG_3)some problems solved with that and always be sure to use utf8_encode on all strings. Regards ChrisAm 08.09.2024 um 15:17 schrieb Flaschenzug ***@***.***>:﻿
Your question
I just started to use zugferd to add xml to bills.
Everything works as expected if I use the example from here: https://github.com/horstoeko/zugferd?tab=readme-ov-file#writing-a-pdf-file-with-attached-xml-file
But If I try to validate the data using this tool: https://validator.invoice-portal.de/
I get the following errors:

general information: XSD Schema: CrossIndustryInvoice (2 errors)

error: Fatal 4 at line 1 > Start tag expected, '<' not found
error: Error 1872 at line -1 > The document has no document element.


Can anyone confirm that this is really happening using the default code?
And if so: Any ideas why and how to solve it?
Thanks :-)

**Comment by horstoeko** [comment]
Hi @Flaschenzug,

> 1. error: Fatal 4 at line 1 > Start tag expected, '<' not found
> 2. error: Error 1872 at line -1 > The document has no document element.

It's Sunday... :-) Don't you have anything better to do on that day than deal with other things? :-) That was a little joke on my part. :-)

My reference for validating the documents is https://www.zugferd-community.net/. The example you mentioned was read in here without errors or warnings. I think that the URL you gave has a bug.

Kind regards.

**Comment by Flaschenzug** [comment]
Thanks and gona check that later (cause I sometimes have better things to do :-P).
And I forgot to mention: The "setDocumentSummation(529.87, 529.87" is wrong - it should be 529.27 ;-)

**Comment by horstoeko** [comment]
Hi @Flaschenzug,,

> When refering to zugferd-community.net -> you mean this tools? https://www.portinvoice.com Or is there another test tool that I can't find? 

Yes, that's exactly what I meant.

> And I forgot to mention: The "setDocumentSummation(529.87, 529.87" is wrong - it should be 529.27 ;-)

indeed, the devil has crept in. I apologize for that. The examples should now be corrected.

Can we close the issue?

Kind regards
