### ISSUE TITLE
[QUESTION] how to set the attached xml filename?

### ISSUE THREAD

**Issue by mgomez-aifinyo** [horstoeko/zugferd#118]
**Context**
I am new to the tool and the standard. I am merging a pdf and an xrechnung xml and I see in example pdfs that the attachment is always named "factur-x.xml", but mines are always named "xrechnung.xml" even if I save the xml to disk with "factur-x.xml" as filename and pass the filename to the merger.

**Question**
The questions are: Does the filename of the attached xml matters for validation? Does it need to be "factur-x.xml" or maybe it depends upon the profile used? How can I specify the attachment filename? I see no method for it.

**Example related code**

```php

public function createZugferdPdf(ZugferdDocumentBuilder $zugferdDocumentBuilder, string $pdfFile, string $outputFilename): string
    {
        // TODO attached xml must be named "factur-x.xml"
        $xmlFileTempPath = $this->tempDir . DIRECTORY_SEPARATOR . 'factur-x.xml';
        $zugferdDocumentBuilder->writeFile($xmlFileTempPath);
        $outputPath = $this->tempDir . DIRECTORY_SEPARATOR . $outputFilename;
        (new ZugferdDocumentPdfMerger($xmlFileTempPath, $pdfFile))->generateDocument()->saveDocument($outputPath);

        return $outputPath;
    }
```

Thanks beforehand!!

**Comment by horstoeko** [comment]
Hi @mgomez-aifinyo 

thank you for the question

> **Context** I am new to the tool and the standard. I am merging a pdf and an xrechnung xml and I see in example pdfs that the attachment is always named "factur-x.xml", but mines are always named "xrechnung.xml" even if I save the xml to disk with "factur-x.xml" as filename and pass the filename to the merger.

The filenames of the attachment are definied by the standard and the format versions. They are defined in [ZugferdProfiles.php](https://github.com/horstoeko/zugferd/blob/master/src/ZugferdProfiles.php)

> **Question** The questions are: Does the filename of the attached xml matters for validation? Does it need to be "factur-x.xml" or maybe it depends upon the profile used? How can I specify the attachment filename? I see no method for it.

Some validators check the version of the document (ZUGFeRD is currently at version 2.2) and deduce the correct attachment file name based on the format specification. However, there are also validators that act a little more freely... :-)

*From the specification:*

_The invoice data is embedded in the PDF/A file in XML format and has a reference via a file specification dictionary to the overall document. In the current version of the Factur-X standard, referencing to only one invoice data document is permitted per PDF/A-3 document invoice data document (designated as “factur-x.xml” or “xrechnung.xml”)._

Kind regards

**Comment by mgomez-aifinyo** [comment]
"OR" that's good :)

But let's say I want to keep it as "factur-x.xml" for consistency with other systems in my environment. Does the zugferd library provide a way to customize the attached filename? 

I see it only internal, not exposed to be set from the document builder or the document merger, for instance.

Thank you very much for your reply and your work!

**Comment by horstoeko** [comment]
Hi @mgomez-aifinyo,

> But let's say I want to keep it as "factur-x.xml" for consistency with other systems in my environment. Does the zugferd library provide a way to customize the attached filename?

No. If I were to allow that, then we would be violating the specification.
 
> I see it only internal, not exposed to be set from the document builder or the document merger, for instance.

see above... :-)
 
Kind regards

**Comment by mgomez-aifinyo** [comment]
Ah, I see. "xrechnung.xml" is also valid then :)

Thank you very much!

**Comment by horstoeko** [comment]
Hi @mgomez-aifinyo ,

No Problem

Kind regards
