### ISSUE TITLE
[BUG] $domDocument->loadXML($this->getXmlContent()) fails silent

### ISSUE THREAD

**Issue by dcrohde** [horstoeko/zugferd#122]
**Describe the bug**
Sometimes $domDocument->loadXML($this->getXmlContent()); fails in extractInvoiceInformations on ZugferdDocumentPdfBuilderAbstract and there is no way to notice. 
First noticeable failure is on $date = $dateXpath->item(0)->nodeValue;

**To Reproduce**

create a document that creates this XML:

`
<?xml version="1.0" encoding="UTF-8"?>
--
  | <rsm:CrossIndustryInvoice xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:a="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:10" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  | <rsm:ExchangedDocumentContext>
  | <ram:BusinessProcessSpecifiedDocumentContextParameter>
  | <ram:ID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</ram:ID>
  | </ram:BusinessProcessSpecifiedDocumentContextParameter>
  | <ram:GuidelineSpecifiedDocumentContextParameter>
  | <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</ram:ID>
  | </ram:GuidelineSpecifiedDocumentContextParameter>
  | </rsm:ExchangedDocumentContext>
  | <rsm:ExchangedDocument>
  | <ram:ID>665932</ram:ID>
  | <ram:TypeCode>380</ram:TypeCode>
  | <ram:IssueDateTime>
  | <udt:DateTimeString format="102">20240901</udt:DateTimeString>
  | </ram:IssueDateTime>
  | <ram:IncludedNote>
  | <ram:Content>Harri -GmbH
  | Heidbergstrasse 100
  | 22846 Norderstedt
  | Deutschland
  | Geschäftsführer: Christoph Burgert
  | Handelsregisternummer: HBR 13060
  |  
  | </ram:Content>
  | <ram:SubjectCode>REG</ram:SubjectCode>
  | </ram:IncludedNote>
  | </rsm:ExchangedDocument>
  | <rsm:SupplyChainTradeTransaction>
  | <ram:IncludedSupplyChainTradeLineItem>
  | <ram:AssociatedDocumentLineDocument>
  | <ram:LineID>1</ram:LineID>
  | <ram:IncludedNote>
  | <ram:Content>Tag- und Nachtschaltung inkl. 400 Gesprächefür den Monat 09.2024</ram:Content>
  | </ram:IncludedNote>
  | </ram:AssociatedDocumentLineDocument>
  | <ram:SpecifiedTradeProduct>
  | <ram:GlobalID schemeID="0160">4012345001235</ram:GlobalID>
  | <ram:SellerAssignedID>SP</ram:SellerAssignedID>
  | <ram:Name>Servicepauschale</ram:Name>
  | </ram:SpecifiedTradeProduct>
  | <ram:SpecifiedLineTradeAgreement>
  | <ram:NetPriceProductTradePrice>
  | <ram:ChargeAmount>625.00</ram:ChargeAmount>
  | </ram:NetPriceProductTradePrice>
  | </ram:SpecifiedLineTradeAgreement>
  | <ram:SpecifiedLineTradeDelivery>
  | <ram:BilledQuantity unitCode="H87">1.00</ram:BilledQuantity>
  | </ram:SpecifiedLineTradeDelivery>
  | <ram:SpecifiedLineTradeSettlement>
  | <ram:ApplicableTradeTax>
  | <ram:TypeCode>VAT</ram:TypeCode>
  | <ram:CategoryCode>S</ram:CategoryCode>
  | <ram:RateApplicablePercent>19.00</ram:RateApplicablePercent>
  | </ram:ApplicableTradeTax>
  | <ram:SpecifiedTradeSettlementLineMonetarySummation>
  | <ram:LineTotalAmount>625.00</ram:LineTotalAmount>
  | </ram:SpecifiedTradeSettlementLineMonetarySummation>
  | </ram:SpecifiedLineTradeSettlement>
  | </ram:IncludedSupplyChainTradeLineItem>
  | <ram:ApplicableHeaderTradeAgreement>
  | <ram:BuyerReference>10097</ram:BuyerReference>
  | <ram:SellerTradeParty>
  | <ram:ID>549910</ram:ID>
  | <ram:GlobalID schemeID="0088">4000001123452</ram:GlobalID>
  | <ram:Name>Harri -GmbH</ram:Name>
  | <ram:DefinedTradeContact>
  | <ram:PersonName>Beate Stahl</ram:PersonName>
  | <ram:DepartmentName>Buchhaltung</ram:DepartmentName>
  | <ram:TelephoneUniversalCommunication>
  | <ram:CompleteNumber>111</ram:CompleteNumber>
  | </ram:TelephoneUniversalCommunication>
  | <ram:EmailURIUniversalCommunication>
  | <ram:URIID>info@harri112.com</ram:URIID>
  | </ram:EmailURIUniversalCommunication>
  | </ram:DefinedTradeContact>
  | <ram:PostalTradeAddress>
  | <ram:PostcodeCode>22846</ram:PostcodeCode>
  | <ram:LineOne>Heidbergstrasse 100</ram:LineOne>
  | <ram:CityName>Norderstedt</ram:CityName>
  | <ram:CountryID>DE</ram:CountryID>
  | </ram:PostalTradeAddress>
  | <ram:URIUniversalCommunication>
  | <ram:URIID schemeID="EM">info@harri112.com</ram:URIID>
  | </ram:URIUniversalCommunication>
  | <ram:SpecifiedTaxRegistration>
  | <ram:ID schemeID="FC">12/290/27729</ram:ID>
  | </ram:SpecifiedTaxRegistration>
  | <ram:SpecifiedTaxRegistration>
  | <ram:ID schemeID="VA">DE123456789</ram:ID>
  | </ram:SpecifiedTaxRegistration>
  | </ram:SellerTradeParty>
  | <ram:BuyerTradeParty>
  | <ram:ID>10097</ram:ID>
  | <ram:Name>Stoltenberg Automobile GmbH &amp; Co. KG</ram:Name>
  | <ram:PostalTradeAddress>
  | <ram:PostcodeCode>12312</ram:PostcodeCode>
  | <ram:LineOne>Harksheider Stra�e 17</ram:LineOne>
  | <ram:CityName>Hamburg</ram:CityName>
  | <ram:CountryID>DE</ram:CountryID>
  | </ram:PostalTradeAddress>
  | <ram:URIUniversalCommunication>
  | <ram:URIID schemeID="EM">test@test.de</ram:URIID>
  | </ram:URIUniversalCommunication>
  | </ram:BuyerTradeParty>
  | </ram:ApplicableHeaderTradeAgreement>
  | <ram:ApplicableHeaderTradeDelivery>
  | <ram:ActualDeliverySupplyChainEvent>
  | <ram:OccurrenceDateTime>
  | <udt:DateTimeString format="102">20240901</udt:DateTimeString>
  | </ram:OccurrenceDateTime>
  | </ram:ActualDeliverySupplyChainEvent>
  | </ram:ApplicableHeaderTradeDelivery>
  | <ram:ApplicableHeaderTradeSettlement>
  | <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
  | <ram:SpecifiedTradeSettlementPaymentMeans>
  | <ram:TypeCode>58</ram:TypeCode>
  | <ram:PayeePartyCreditorFinancialAccount>
  | <ram:IBANID>DE12500105170648489890</ram:IBANID>
  | </ram:PayeePartyCreditorFinancialAccount>
  | </ram:SpecifiedTradeSettlementPaymentMeans>
  | <ram:ApplicableTradeTax>
  | <ram:CalculatedAmount>118.75</ram:CalculatedAmount>
  | <ram:TypeCode>VAT</ram:TypeCode>
  | <ram:BasisAmount>625.00</ram:BasisAmount>
  | <ram:CategoryCode>S</ram:CategoryCode>
  | <ram:RateApplicablePercent>19.00</ram:RateApplicablePercent>
  | </ram:ApplicableTradeTax>
  | <ram:SpecifiedTradePaymentTerms>
  | <ram:Description>Bitte überweisen Sie den überweisen</ram:Description>
  | </ram:SpecifiedTradePaymentTerms>
  | <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
  | <ram:LineTotalAmount>625.00</ram:LineTotalAmount>
  | <ram:ChargeTotalAmount>0.00</ram:ChargeTotalAmount>
  | <ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
  | <ram:TaxBasisTotalAmount>625.00</ram:TaxBasisTotalAmount>
  | <ram:TaxTotalAmount currencyID="EUR">118.75</ram:TaxTotalAmount>
  | <ram:GrandTotalAmount>743.75</ram:GrandTotalAmount>
  | <ram:TotalPrepaidAmount>0.00</ram:TotalPrepaidAmount>
  | <ram:DuePayableAmount>743.75</ram:DuePayableAmount>
  | </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
  | </ram:ApplicableHeaderTradeSettlement>
  | </rsm:SupplyChainTradeTransaction>
  | </rsm:CrossIndustryInvoice>

`

**Expected behavior**
My expectation actually was that this XML is parable as its also created with the library.
**Screenshots**

**Sample Code
I used this code, sorry its not very clean:

`	 $document = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_XRECHNUNG_3	);
    $document
    ->setDocumentInformation($data['rid'], "380", (new DateTime())->setTimestamp($temp[0]['rid_rechnungsdatum']), "EUR")
    //->addDocumentNote('Rechnung gemäß Bestellung vom 01.03.2018.')
    ->addDocumentNote('Harri -GmbH' . PHP_EOL . 'Heidbergstrasse 100' . PHP_EOL . '22846 Norderstedt' . PHP_EOL . 'Deutschland' . PHP_EOL . 'Geschäftsführer: Christoph Burgert' . PHP_EOL . 'Handelsregisternummer: HBR 13060' . PHP_EOL . PHP_EOL, null, 'REG')
	->setDocumentBusinessProcess('urn:fdc:peppol.eu:2017:poacc:billing:01:1.0')
    ->setDocumentSupplyChainEvent((new DateTime())->setTimestamp($temp[0]['rid_rechnungsdatum']))
    ->addDocumentPaymentMean(ZugferdPaymentMeans::UNTDID_4461_58, null, null, null, null, null, "DE12500105170648489890", null, null, null)
    ->setDocumentSeller("Harri -GmbH", "549910")

    ->setDocumentSellerContact("Beate Stahl", "Buchhaltung", "111", "222","info@harri112.com")
    ->addDocumentSellerGlobalId("4000001123452", "0088")
    ->addDocumentSellerTaxRegistration("FC", "12/290/27729")
    ->addDocumentSellerTaxRegistration("VA", "DE123456789")
    ->setDocumentSellerAddress("Heidbergstrasse 100", "", "", "22846", "Norderstedt", "DE")
    ->setDocumentSellerCommunication("EM",'info@harri112.com')

    //->setDocumentSellerTaxRepresentativeTradeParty("Tax Representative", "123", "Tax Representative Description")
    //->setDocumentSellerTaxRepresentativeAddress("Street 1", "", "", "11111", "Representative City", "DE", "Bayern")
    ->setDocumentBuyer($zeile[0], $data['Kundennr'])
    ->setDocumentBuyerReference($data['Kundennr'])
    ->setDocumentBuyerAddress( $zeile[1], "", "", "12312",  substr($zeile[2],6), "DE")
	->setDocumentBuyerCommunication('EM', 'test@test.de')
    ->addDocumentTax("S", "VAT", $temp[0]['rid_betragnetto'], $temp[0]['rid_betragnetto']*0.19, 19.0)

    
    
    ->addDocumentPaymentTerm(
    
    ($kunde[0]['zahlungsart']=="L")
    ?"Der Betrag wird ".
    	(
    		($this->kind=="G")
    		?"verrechnet."
			:"eingezogen"
		)
	:'Bitte überweisen Sie den überweisen'
    )
    ;
    
    for ($i=0;$i<count($artikel);$i++){
      
       $document->addNewPosition($i+1) 
     
    ->setDocumentPositionProductDetails($artikel[$i]['aid_bezeichnung'], "", $artikel[$i]['aid_kurz'], null, "0160", "4012345001235")

        ->setDocumentPositionNetPrice($artikel[$i]['aid_preis'])
    ->setDocumentPositionQuantity($artikel[$i]['rdid_menge'], "H87")
    ->addDocumentPositionTax('S', 'VAT', 19)
    ->setDocumentPositionLineSummation($artikel[$i]['rdid_menge'] * $artikel[$i]['aid_preis']);
    
        $textbausteine = DB::getdata_from_sql("SELECT * FROM buchhaltung_vor_textbausteine WHERE tid_rdid = ".$artikel[$i]['rdid']." ORDER BY tid ASC");
        $text = '';
      for ($j=0;$j<count($textbausteine);$j++){ 

			$text .= $textbausteine[$j]['rdid_text'];
      }
    $document->setDocumentPositionNote($text);   
    }
    
    $document->setDocumentSummation(
    $temp[0]['rid_betragnetto']*1.19
    ,$temp[0]['rid_betragnetto']*1.19
    , $temp[0]['rid_betragnetto']
    , 0.0
    , 0.0
    , $temp[0]['rid_betragnetto']
    , $temp[0]['rid_betragnetto'] * 0.19
    , null, 0.0);

    $pdfBuilder = new ZugferdDocumentPdfBuilder($document,$pdf_name);
    if (file_exists($pdf_name)){
		$pdfBuilder->generateDocument()->saveDocument($pdf_name);	    
    }else{
	    echo "Fehler beim XML gnerieren";
    }
`

**Additional information:**

 - PHP-Version 8.2

**Additional context**

**Comment by dcrohde** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<rsm:CrossIndustryInvoice xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100" xmlns:a="urn:un:unece:uncefact:data:standard:QualifiedDataType:100" xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:10" xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <rsm:ExchangedDocumentContext>
    <ram:BusinessProcessSpecifiedDocumentContextParameter>
      <ram:ID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</ram:ID>
    </ram:BusinessProcessSpecifiedDocumentContextParameter>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>
  <rsm:ExchangedDocument>
    <ram:ID>665932</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">20240901</udt:DateTimeString>
    </ram:IssueDateTime>
    <ram:IncludedNote>
      <ram:Content>Harri -GmbH
Heidbergstrasse 100
22846 Norderstedt
Deutschland
Geschäftsführer: Christoph Burgert
Handelsregisternummer: HBR 13060

</ram:Content>
      <ram:SubjectCode>REG</ram:SubjectCode>
    </ram:IncludedNote>
  </rsm:ExchangedDocument>
  <rsm:SupplyChainTradeTransaction>
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>1</ram:LineID>
        <ram:IncludedNote>
          <ram:Content>Tag- und Nachtschaltung inkl. 400 Gesprächefür den Monat 09.2024</ram:Content>
        </ram:IncludedNote>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:GlobalID schemeID="0160">4012345001235</ram:GlobalID>
        <ram:SellerAssignedID>SP</ram:SellerAssignedID>
        <ram:Name>Servicepauschale</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>625.00</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="H87">1.00</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>S</ram:CategoryCode>
          <ram:RateApplicablePercent>19.00</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>625.00</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
    <ram:ApplicableHeaderTradeAgreement>
      <ram:BuyerReference>10097</ram:BuyerReference>
      <ram:SellerTradeParty>
        <ram:ID>549910</ram:ID>
        <ram:GlobalID schemeID="0088">4000001123452</ram:GlobalID>
        <ram:Name>Harri -GmbH</ram:Name>
        <ram:DefinedTradeContact>
          <ram:PersonName>Beate Stahl</ram:PersonName>
          <ram:DepartmentName>Buchhaltung</ram:DepartmentName>
          <ram:TelephoneUniversalCommunication>
            <ram:CompleteNumber>111</ram:CompleteNumber>
          </ram:TelephoneUniversalCommunication>
          <ram:EmailURIUniversalCommunication>
            <ram:URIID>info@harri112.com</ram:URIID>
          </ram:EmailURIUniversalCommunication>
        </ram:DefinedTradeContact>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>22846</ram:PostcodeCode>
          <ram:LineOne>Heidbergstrasse 100</ram:LineOne>
          <ram:CityName>Norderstedt</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:URIUniversalCommunication>
          <ram:URIID schemeID="EM">info@harri112.com</ram:URIID>
        </ram:URIUniversalCommunication>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="FC">12/290/27729</ram:ID>
        </ram:SpecifiedTaxRegistration>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">DE123456789</ram:ID>
        </ram:SpecifiedTaxRegistration>
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:ID>10097</ram:ID>
        <ram:Name>Stoltenberg Automobile GmbH &amp; Co. KG</ram:Name>
        <ram:PostalTradeAddress>
          <ram:PostcodeCode>12312</ram:PostcodeCode>
          <ram:LineOne>Harksheider Stra�e 17</ram:LineOne>
          <ram:CityName>Hamburg</ram:CityName>
          <ram:CountryID>DE</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:URIUniversalCommunication>
          <ram:URIID schemeID="EM">test@test.de</ram:URIID>
        </ram:URIUniversalCommunication>
      </ram:BuyerTradeParty>
    </ram:ApplicableHeaderTradeAgreement>
    <ram:ApplicableHeaderTradeDelivery>
      <ram:ActualDeliverySupplyChainEvent>
        <ram:OccurrenceDateTime>
          <udt:DateTimeString format="102">20240901</udt:DateTimeString>
        </ram:OccurrenceDateTime>
      </ram:ActualDeliverySupplyChainEvent>
    </ram:ApplicableHeaderTradeDelivery>
    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>58</ram:TypeCode>
        <ram:PayeePartyCreditorFinancialAccount>
          <ram:IBANID>DE12500105170648489890</ram:IBANID>
        </ram:PayeePartyCreditorFinancialAccount>
      </ram:SpecifiedTradeSettlementPaymentMeans>
      <ram:ApplicableTradeTax>
        <ram:CalculatedAmount>118.75</ram:CalculatedAmount>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:BasisAmount>625.00</ram:BasisAmount>
        <ram:CategoryCode>S</ram:CategoryCode>
        <ram:RateApplicablePercent>19.00</ram:RateApplicablePercent>
      </ram:ApplicableTradeTax>
      <ram:SpecifiedTradePaymentTerms>
        <ram:Description>Bitte überweisen Sie den überweisen</ram:Description>
      </ram:SpecifiedTradePaymentTerms>
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:LineTotalAmount>625.00</ram:LineTotalAmount>
        <ram:ChargeTotalAmount>0.00</ram:ChargeTotalAmount>
        <ram:AllowanceTotalAmount>0.00</ram:AllowanceTotalAmount>
        <ram:TaxBasisTotalAmount>625.00</ram:TaxBasisTotalAmount>
        <ram:TaxTotalAmount currencyID="EUR">118.75</ram:TaxTotalAmount>
        <ram:GrandTotalAmount>743.75</ram:GrandTotalAmount>
        <ram:TotalPrepaidAmount>0.00</ram:TotalPrepaidAmount>
        <ram:DuePayableAmount>743.75</ram:DuePayableAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>
</rsm:CrossIndustryInvoice>`


Better formatted

**Comment by dcrohde** [comment]
I'm too stupid to paste the XML properly

[example.txt](https://github.com/user-attachments/files/17102836/example.txt)

**Comment by horstoeko** [comment]
Hi @dcrohde,

Hi,

sorry, but unfortunately I can't do anything with this issue because it's too chaotic. Please structure the issues so that you can recognize what the problem is without spending a lot of time.

Best regards
