### ISSUE TITLE
[QUESTION] How can I add taxes from other countries

### ISSUE THREAD

**Issue by MarlonGnauck** [horstoeko/zugferd#123]
I have invoices with taxes from other countries. So I must calculate the tax from france when I ship a parcel and I have no TAXId from the reciver of the parcel... 

How can I set the TaxCountry?

PS: Ich glaube ich schreibe mit jemanden der Deutsch kann ;-) Das ganze nennt sich OSS-Verfahren und ich muss die MwSt der Lieferländer abrechnen wenn ich nicht eindeutig nachweisen kann das es sich beim Rechnungsempfänger um eine Firma handelt... Sobald ich eine USTId vom Rechnungsempfänger habe ist es einfach dann wird die deutsche MwSt für die Pakete berechnet...

Aktuell benutze ich die exemptionReason um den Sachverhalt als Text zu erklären...

**Comment by horstoeko** [comment]
Hello @MarlonGnauck 

that's a very good question. I haven't actually dealt with this topic yet. Is it about sending or receiving invoices?

**Comment by MarlonGnauck** [comment]
Sending invoice

**Comment by horstoeko** [comment]
HI @MarlonGnauck,

... that was a short answer :-) As already mentioned, I have never dealt with this topic before. If you are only interested in displaying the tax amount in a foreign currency, then you can use the ``ZugferdDocumentBuilder::setForeignCurrency`` method. Otherwise, we can only hope that one of the other users of this library has already dealt with this topic.

Kind regards

**Comment by MarlonGnauck** [comment]
The answer was almost long considering the time ;-)

I've read up on the Zugferd format, it's simply not intended... So I made the request directly again via the Zugferd community in order to, in the best case scenario, achieve an extension of the standard.

https://www.zugferd-community.net/forum/viewtopic.php?t=184

**Comment by horstoeko** [comment]
Hi @MarlonGnauck,

I'm glad to read and hear that... As I said - if I wanted to soak up everything to do with tax, I would have become a tax consultant... :-)

I'll keep my fingers crossed for you, but I'm afraid that it won't lead to success. In my personal opinion, the topic of “e-invoicing” has been approached completely wrongly in Germany. They should have taken Italy as an example...

Best regards
