### ISSUE TITLE
[QUESTION] SpecifiedLogisticsServiceCharge

### ISSUE THREAD

**Issue by MarlonGnauck** [horstoeko/zugferd#126]
Is there an example for recording (multiple) shipping costs in one invoice?

Thank you very much

**Comment by horstoeko** [comment]
Hi @MarlonGnauck,

I have only found examples in the official documentation that include a single assignment of service fees. However, my library also supports multiple assignment - see ``ZugferdDocumentBuilder::addDocumentLogisticsServiceCharge``. The ZugferdDocumentReader also supports service charges in the multiple assignment. There are tests for this ([here](https://github.com/horstoeko/zugferd/blob/f46e9641b1fb564339d04cf43c7200a5a134e112/tests/testcases/BuilderExtendedTest.php#L1585) and [here](https://github.com/horstoeko/zugferd/blob/f46e9641b1fb564339d04cf43c7200a5a134e112/tests/testcases/ReaderExtendedTest.php#L993)I. Maybe that will help you?

Please note that service fees are only supported in the EXTENDED profile. These are not provided for in the EN16931 (COMFORT) and XRechnung profiles.

Kind regards

**Comment by MarlonGnauck** [comment]
Many thanks for the quick response.

A question for understanding... Why are category, VAT and type passed as an array? An entry cannot have more than one tax rate.

However, the realization at the end is that the validator throws so many errors that I am currently going to deposit it as an SAA type surcharge. That's fundamentally not right, but it's not wrong either ;-)

**Comment by horstoeko** [comment]
> A question for understanding... Why are category, VAT and type passed as an array? An entry cannot have more than one tax rate.

In fact, it is possible to deposit several tax rates for one service fee. Here is an excerpt from the official documentation:

![image](https://github.com/user-attachments/assets/370d86e2-ecaa-4cee-9d29-d79f9ba4b965)

Nice if I could help. Does this answer the question completely?

Kind regards
