### ISSUE TITLE
[FEATURE] xinvoice xml to zugferd xml

### ISSUE THREAD

**Issue by DAThosting** [horstoeko/zugferd#127]
**Describe the feature**
Thank you very much for this library.
We still have the problem that the ERP of a customer can output xRechnung, but the customer would like to have Zugferd.
Is there a way to convert an xInvoice XML into a Zugferd XML?

**Expected behavior**
xInvoice XML input => zugferd XML output

**Comment by horstoeko** [comment]
Hi @DAThosting,

Thank you for your question. In fact, I don't really understand the “problem” yet. Is the customer just missing the PDF with the embedded XML?

Kind regards?

**Comment by DAThosting** [comment]
Hi,

as far as I know, the structure of an xInvoice XML is not the same as that of a train ground XML, or am I wrong?

Can I then simply merge the xInvoice XML into an existing PDF, as it is stored here in the library?

**Comment by horstoeko** [comment]
Hi @DAThosting,

ZUGFeRD also recognizes the “XRechnung” profile (I simply assume that by XInvoice you actually mean XRechnung). The ``ZugferdDocumentPdfMerger`` should recognize this correctly.
