### ISSUE TITLE
[BUG] MINIMUM - SetDocumentSummation result in GrandTotalAmount is not expected

### ISSUE THREAD

**Issue by TTP1106** [horstoeko/zugferd#128]
**Describe the bug**
If I use the Minimum Profile, then  I get an error on SetDocumentSummation() because it will send GrandTotalAmount but this it not expected in the profile.

**To Reproduce**
```php
try {
    // Erstelle ein Zugferd-Dokument mit dem MINIMUM-Profil
    $builder = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_MINIMUM);

    // Dokumentinformationen hinzufügen
    $builder->SetDocumentInformation("R-230001_K-100003", "380", \DateTime::createFromFormat("Ymd", "20240906"), "EUR");

    // Lieferant/Verkäufer Informationen hinzufügen
    $builder->setDocumentSeller("Company.de", "000000")
        ->addDocumentSellerTaxRegistration("FC", "19/103/10109");

    // Kunde/Käufer Informationen hinzufügen
    $builder->setDocumentBuyer("Kunden AG Frankreich", "000001");

    // Kaufreferenz hinzufügen (optional)
    //$builder->SetBuyerReference("BUYERREF");

    // Rechnungsbeträge hinzufügen
    //($grandTotalAmount, $duePayableAmount, $lineTotalAmount, $chargeTotalAmount, $allowanceTotalAmount, $taxBasisTotalAmount,$taxTotalAmount, $roundingAmount, $totalPrepaidAmount)
    $builder->SetDocumentSummation(119.00, 119.00, 0);

    // Speichere das Dokument als XML
    $xmlOutputPath = __DIR__ . '/factur-x.xml';
    $builder->writeFile($xmlOutputPath);
    echo "Factur-X XML wurde erfolgreich erstellt: $xmlOutputPath\n";

    //Validate
    $document = ZugferdDocumentReader::readAndGuessFromFile($xmlOutputPath);
    $xsdValidator = new ZugferdXsdValidator($document);
    $xsdValidator->validate();
    echo "<br>\nValidate: " . var_export($xsdValidator->validationPased(), 1) . "<br>\n";
    echo "<br>\n" . var_dump($xsdValidator->validationErrors());
   //Check error
} catch (Exception $e) {
    echo "Fehler beim Erstellen der Factur-X XML: " . $e->getMessage() . "\n";
}
```

**Expected behavior**
 Element '{urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}GrandTotalAmount': This element is not expected. Expected is ( {urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100}TaxBasisTotalAmount ). " }.

**Additional information:**
 - OS: Debian
 - PHP-Version PHP8

Seems that the Function is not compliant with PROFILE_MINIMUM

**Comment by horstoeko** [comment]
Hi @TTP1106 ,

The problem is that you have forgotten to enter ``taxBasisTotalAmount ``. This is a mandatory entry according to the specification.

![grafik](https://github.com/user-attachments/assets/299301af-9ad0-45c3-b6df-70ca09a39718)

Change your code:

```php
$builder->SetDocumentSummation(119.00, 119.00, 0, null, null, 100.0);
```

![grafik](https://github.com/user-attachments/assets/f0784c60-d1ca-4dca-bec9-4b40c926220a)

... and everything works as expected. :

``
Factur-X XML wurde erfolgreich erstellt: /xxxxxxxxxxxxxxxx/factur-x.xml
<br>
Validate: true<br>
/xxxxxxxxxxxxxxxx/Example2.php:41:
array(0) {
}
<br>
``

The validation was not wrong, so to speak
