### ISSUE TITLE
[QUESTION] Calling generateDocument() on ZugferdDocumentPdfMerger fails

### ISSUE THREAD

**Issue by espressodriven** [horstoeko/zugferd#129]
**Describe the bug**
When I call generateDocument() on a ZugferdDocumentPdfMerger, I get the error 'Invalid data after startxref keyword.'
I have already tried dozens of PDFs for my tests, including the test documents provided with this project, but the issue persists.

**To Reproduce**
Call generateDocument() on a ZugferdDocumentPdfMerger as documented in the wiki of the project: https://github.com/horstoeko/zugferd?tab=readme-ov-file#merge-existing-pdf-and-xml

**Expected behavior**
The merged document is generated, and I can save it in the next step.

**Screenshots**
none

**Sample Code**

```php
use horstoeko\zugferd\ZugferdDocumentPdfMerger;

require dirname(__FILE__) . "/../vendor/autoload.php";

$existingXml = dirname(__FILE__) . "/invoice_1.xml";
$existingPdf = dirname(__FILE__) . "/emptypdf.pdf";
$mergeToPdf = dirname(__FILE__) . "/fullpdf.pdf";

if (!file_exists($existingXml) || !file_exists($existingPdf)) {
    throw new \Exception("XML and/or PDF does not exist");
}

(new ZugferdDocumentPdfMerger($existingXml, $existingPdf))->generateDocument()->saveDocument($mergeToPdf);
```

**Additional information:**
 - OS: Windows
 - OS-Version: 11
 - PHP-Version: 7.4.33

**Comment by horstoeko** [comment]
Hi @espressodriven,

I can't see any bug... There are a lot of integration tests running. I suspect that your PDFs are all defective. That's the only thing I can assume at the moment, since you haven't included any meaningful example code, let alone an example PDF. I am at a loss.

Kind regards

**Comment by espressodriven** [comment]
Hi @horstoeko 

thank you for your prompt reply and looking into it. I really appreciate that.
I am sorry that I might have been not concise enough about my usage of the library. I have attached the pdf and the xml file I have used for testing.
As for the example code, I have used the code you provided in the readme of the project. Of course I have adjusted the filenames to match the ones that I provided, but otherwise, it is exactly the same. I have also included that in the issue-description.

Kind Regards.

[TestFiles.zip](https://github.com/user-attachments/files/17202899/TestFiles.zip)

**Comment by horstoeko** [comment]
Hi @espressodriven.

I have now written a small test and used the two files that you kindly made available to me. I did not get an error as you described. By the way, the error you mentioned comes from a PDFParser library that I use and not directly from my library. The PDF file seems to me to be very small anyway.

Unfortunately, I am at a bit of a loss. Maybe you have the chance to work with a more modern PHP version. You might have some success with that.

Best regards

**Comment by horstoeko** [comment]
Hi @espressodriven,

could you solve the problem?

**Comment by espressodriven** [comment]
Hi @horstoeko 

No, unfortunately I am bound to PHP 7.4 for the time beeing. I did not find any workaround that did work for me.
Thank you again for your assistance!

**Comment by horstoeko** [comment]
Hi @espressodriven,

OK. Unfortunately, that's not nice, but it can't be helped. Good luck and if you have any other questions, I look forward to reading from you again...

Best regards
