### ISSUE TITLE
Missing functions in ZugferdDocumentReader.php to get electronic address (BT-34, BT-49)

### ISSUE THREAD

**Issue by sanchr** [horstoeko/zugferd#136]
The following functions are missing in ZugferdDocumentReader.php to get the Seller electronic address (BT-34) an the Buyer electronic address (BT-49):

getDocumentSellerCommunication
getDocumentBuyerCommunication

I have attached a possible solution as a snippet, which can perhaps be integrated into the file ZugferdDocumentReader.php

[snippet.pdf](https://github.com/user-attachments/files/17339932/snippet.pdf)

**Comment by horstoeko** [comment]
Hi @sanchr,

Thanks for the tip. I will implement this in the near future.

Kind regards
