### ISSUE TITLE
Handling of the new german "Wirtschafts-Identifikationsnummer" ("business identification number")

### ISSUE THREAD

**Issue by AvengerD** [horstoeko/zugferd#142]
First of all I would like to thank you very for making this great software publicly available, it really eases the job of creating an e-invoice functionality into our shop very much for me.

No chance to do that without it....

So far, I have already been able to extract all the information needed for an e-invoice from orders in our shop, and set up the calls to the necessary "ZugferdDocumentBuilder" methods....

And then comes testing and debugging...

=============================================

Here is my question:

Gradually, all companies in Germany will be assigned a "Wirtschafts-Identifikationsnummer" ("business identification number") by the tax authorities.

This number MUST be stated on invoices (and other documents), like e.g. the tax number.

Can this already be included with the current software version (how?), or does a software update have to be done for this?

[(https://www.bzst.de/DE/Unternehmen/Identifikationsnummern/Wirtschafts-Identifikationsnummer/wirtschaftsidentifikationsnummer.html)]((https://www.bzst.de/DE/Unternehmen/Identifikationsnummern/Wirtschafts-Identifikationsnummer/wirtschaftsidentifikationsnummer.html))

**Comment by horstoeko** [comment]
Hi,

>First of all I would like to thank you very for making this great software publicly available, it really eases the job of creating an e-invoice functionality into our shop very much for me.

I'm delighted that my library is helping you so much. This is a great endorsement of my work. Thank you very much for the kind words.

> Gradually, all companies in Germany will be assigned a "Wirtschafts-Identifikationsnummer" ("business identification number") by the tax authorities.

I am not aware of any plans or prospects for transmitting this number. If I am not mistaken, then this is not part of an electronic invoice but is much more within your sphere of action (keyword: reporting)

The official documentation and the relevant forums do not provide any information in this regard.

Unfortunately, I can't say any more about this. If this ID is to become part of an electronic invoice in the future, we will of course be very happy to implement it. If you should receive any further information, I would be very happy to hear from you

Kind regards

**Comment by horstoeko** [comment]
Hi @AvengerD,

A small idea on my part: What could be a possibility from my point of view would be to specify the number under __SpecifiedTaxRegistration__ with the schemeID “ZZZ”.

```php
->addDocumentSellerTaxRegistration("ZZZ", "<Your W-ID-Number>")
```

Technically this should work, but whether the validators can cope with it would still have to be checked.

Kind regards
