### ISSUE TITLE
Problem with "setDocumentInformation"

### ISSUE THREAD

**Issue by AvengerD** [horstoeko/zugferd#144]
On my first attempt to debug my code to create an e-invoice, I run into the following problem with "setDocumentInformation":

( ! ) Fatal error: Uncaught TypeError: Argument 3 passed to horstoeko\zugferd\ZugferdDocumentBuilder::setDocumentInformation() must be an instance of DateTime, boolean given, 

called in [...]prepare_e_invoices.php on line 69 and defined in [...]vendor\horstoeko\zugferd\src\ZugferdDocumentBuilder.php on line 182

**Sample Code

Following the example in the documentation

  // Add invoice and position information
  $document
    ->setDocumentInformation("471102", "380", \DateTime::createFromFormat("Ymd", "20180305"), "EUR")

my code looks like this:

$invoice_date=date("Ymd");   //"20241018"
$document
  ->setDocumentInformation($order_id, "380", \DateTime::createFromFormat("Ymd", $invoice_date), "EUR")

Why PHP thinks, that "\DateTime::createFromFormat("Ymd", $invoice_date)" is of type "boolean"?

What am I doing wrong???

**Comment by wblessen** [comment]
createFromFormat()

Parse a string into a new DateTime object according to the specified format
Parameters:
string $format – Format accepted by date(). string $datetime – String representing the time. DateTimeZone|null $timezone – A DateTimeZone object representing the desired time zone.
Returns:
DateTime|false 

$invoice_date does not seem to be valid. You must check the DateTime first, before inserting it.

**Comment by AvengerD** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-size:14px;font-family:times new roman, times, serif;;}Hi, Wolfgang,thx for your answer."$invoice_date" IS a string, created with "date()"... (https://www.php.net/manual/en/function.date.php)I can verify this in my debugging environment.How else could I create a string acceptable for DateTime for the invoice date?
Wolfgang Blessen schrieb am 18.10.2024 11:56 (GMT +02:00):

createFromFormat()
Parse a string into a new DateTime object according to the specified formatParameters:string $format – Format accepted by date(). string $datetime – String representing the time. DateTimeZone|null $timezone – A DateTimeZone object representing the desired time zone.Returns:DateTime|false 
$invoice_date does not seem to be valid. You must check the DateTime first, before inserting it.

**Comment by horstoeko** [comment]
Hi @AvengerD,

I think that the question is not related to my library but it is a general technical understanding problem. I will close this issue now.

Kind regards
