### ISSUE TITLE
[QUESTION] Zugferd extended profile (2.0) not supported

### ISSUE THREAD

**Issue by DanielRuf** [horstoeko/zugferd#150]
**Describe the bug**
It seems the profile `urn:cen.eu:en16931:2017#conformant#urn:zugferd.de:2p0:extended` is not supported.

**To Reproduce**
Parse a PDF file with `urn:cen.eu:en16931:2017#conformant#urn:zugferd.de:2p0:extended` profile.

**Expected behavior**
I expect to be able to parse PDF files with the mentioned profile.

**Additional information:**
 - OS: Windows
 - OS-Version: Windows11
 - PHP-Version: 8.1

**Additional context**
Not sure, if this profile is (still) relevant or if the new regulation allows only other profiles.

**Comment by horstoeko** [comment]
Hi @DanielRuf

without any Demo file i am not able to help you. I also don't see a qualified error message or anything similar anywhere. Ultimately, the issue is just a statement for me. In addition, Zugferd 2.0 has expired.

Please provide the necessary information

**Comment by DanielRuf** [comment]
> In addition, Zugferd 2.0 has expired.

So does that mean that new E-Invoices should not be created with this or is not allowed anymore?

I've received a file with this profile, but this leads to `throw new ZugferdUnknownProfileException((string)$typeelement[0]);` due to the missing profile definition.

**Comment by horstoeko** [comment]
Hi @DanielRuf,

In fact, the submitted profile is already very old (I recommend reading [this link](https://de.wikipedia.org/wiki/ZUGFeRD#Historie) :-) According to your information, it is (presumably) version 2.0.1 - we currently have 2.3. Cardinalities and/or similar have changed in between, which in my view makes it almost impossible to read it into the existing structure. Did you get the file from a supplier?

**Comment by DanielRuf** [comment]
> Did you get the file from a supplier?

Yes, with an invoice date of ` 06.02.2024`.

**Comment by horstoeko** [comment]
Hi @DanielRuf,

The version has really expired. I would recommend that you reject the document. 

Can we consider this issue closed?

Kind regards

**Comment by DanielRuf** [comment]
Thanks for the confirmation, that this profile has expired.

I will clarify that and let you know tomorrow, if this issue can be closed. Due to the size of the involved parties who may send the invoice with this profile, we probably have not many options.

If you know an alternative path to support this profile in PHP environments, please let me know.

**Comment by horstoeko** [comment]
Hi @DanielRuf,

> If you know an alternative path to support this profile in PHP environments, please let me know.

Thanks for the feedback. I can try to include the context parameters of the old ZUGFeRD 2.0 version in the recognition of the profile. However, it is possible that the deserialization of the XML into the internal object structure may fail due to changes in cardinalities (or similar) in the meantime.

> I will clarify that and let you know tomorrow, if this issue can be closed. Due to the size of the involved parties who may send the invoice with this profile, we probably have not many options.

I look forward to hearing back from you.

**Comment by DanielRuf** [comment]
I think we can close this issue for now.

BMF states at least 2.0.1 can be used for the upcoming requirements.

See § 25 at https://www.bundesfinanzministerium.de/Content/DE/Downloads/BMF_Schreiben/Steuerarten/Umsatzsteuer/2024-10-15-einfuehrung-e-rechnung.pdf?__blob=publicationFile&v=1

**Comment by horstoeko** [comment]
Hi @DanielRuf,

I have also included the “obsolete” profiles. Please take a look at the PR #151. As I said, there might be problems with cardinalities and so on, but I think everything will be fine... :-)

Kind regards

**Comment by DanielRuf** [comment]
> Please take a look at the PR https://github.com/horstoeko/zugferd/pull/152

Thanks, I will check that.
