### ISSUE TITLE
[QUESTION] multiple SpecifiedTradePaymentTerms for XRECHNUNG

### ISSUE THREAD

**Issue by stiefelsalat** [horstoeko/zugferd#151]
Is it possible to set multiple _SpecifiedTradePaymentTerms_ for XRECHNUNG (2.2)? I have seen that en16931\ram\HeaderTradeSettlementType only hat the setSpecifiedTradePaymentTerms() function but not the addToSpecifiedTradePaymentTerms() function. As far as i've understood the profile usually accepts multiple SpecifiedTradePaymentTerms.  Is there a reason for that why it is not possible here? 

Also the function addDiscountTermsToPaymentTerms() doesnt seem to add the data to the previously added PaymentTerm. But i guess it is linked to the multiple PaymentTerms question.

**Comment by horstoeko** [comment]
Hi @stiefelsalat,

To the best of my current knowledge, XRechnung is based on the EN16931 profile (“COMFORT”), which does not allow multiple assignment of payment terms. 

![grafik](https://github.com/user-attachments/assets/ad73f046-d310-4f59-b469-7c56d06b8130)

Can we now consider this issue to be resolved?

Kind regards

**Comment by stiefelsalat** [comment]
Hi @horstoeko ,

It seems that i wasn't using the correct documentation then, so yes the issue is resolved.

Thanks for the help!

**Comment by horstoeko** [comment]
Hi @stiefelsalat,

thank you for your response.

Kind regards
