### ISSUE TITLE
[QUESTION] How to use addNewTextPosition

### ISSUE THREAD

**Issue by squadt** [horstoeko/zugferd#154]
**Your question**
There is no example code for $document->addNewTextPosition(...).
With the code below, the code is missing in the XML file, and the validator reports that it requires amount, price, quantity, etc. 

**Sample Code**
```
$document
          ->addNewTextPosition("1", "TYPE_LINE", "information") // $lineStatusCode = null or any other string
          ->setDocumentPositionProductDetails("Position 1");
```

```
$document->getDocumentPositionGenerals($lineid, $linestatuscode, $linestatusreasoncode);
// $linestatuscode, $linestatusreasoncode will be empty
```

**Additional context**
using PROFILE_XRECHNUNG_3
on v1.0.73

**Comment by horstoeko** [comment]
Hi @squadt,

this is a relic from the old ZUGFeRD v1 times. This method should no longer be used. I will mark it as deprecated.

Kind regards
