### ISSUE TITLE
[QUESTION] Question regarding BusinessProcessSpecifiedDocumentContextParameter (BT-23)

### ISSUE THREAD

**Issue by sanchr** [horstoeko/zugferd#159]
I have a question of comprehension about the BusinessProcessSpecifiedDocumentContextParameter field in the profile EXTENDED:
According to the specification ZUGFeRD 2.3 / Factur-X 1.0.07 - Profile EXTENDED, the field has a different cardinality of 1..1, so the field should be a mandatory field.

In your examples I see that this field can be supplied like this: 
$document->setDocumentBusinessProcess(‘urn:fdc:peppol.eu:2017:poacc:billing:01:1.0’);

But would it perhaps also make sense to set the default value already in the ZugferdProfiles:
self::PROFILE_EXTENDED => [
  ‘businessprocess’ => ‘urn:fdc:peppol.eu:2017:poacc:billing:01:1.0’
]

Another point: you recently asked how or for what purpose we use your library.
I can no longer find this enquiry, but would be happy to answer you.
Where can I find this enquiry?

[8. Factur-X_1.0.07_Technischer-Anhang_Profil_EXTENDED.pdf](https://github.com/user-attachments/files/17612322/8.Factur-X_1.0.07_Technischer-Anhang_Profil_EXTENDED.pdf)

**Comment by horstoeko** [comment]
Hi @sanchr,

thank you for your question.

> I have a question of comprehension about the BusinessProcessSpecifiedDocumentContextParameter field in the profile EXTENDED: According to the specification ZUGFeRD 2.3 / Factur-X 1.0.07 - Profile EXTENDED, the field has a different cardinality of 1..1, so the field should be a mandatory field.

As far as I know, the information is currently only mandatory for an XRechnung. If you have any other information, please let me know. 

> But would it perhaps also make sense to set the default value already in the ZugferdProfiles: self::PROFILE_EXTENDED => [ ‘businessprocess’ => ‘urn:fdc:peppol.eu:2017:poacc:billing:01:1.0’ ]

I can add this to the profile definition (at least for the extended profile).
 
> Another point: you recently asked how or for what purpose we use your library. I can no longer find this enquiry, but would be happy to answer you. Where can I find this enquiry?

As the e-mail address for the survey was unfortunately also used for other things, I have deactivated it again. However, you can find a mail address in the sources of my library.

Kind regards

**Comment by horstoeko** [comment]
Hi @sanchr,

please review [this commit](https://github.com/horstoeko/zugferd/commit/1646873d55fb5a7ca15ea4b51f5a1d4c8c754c17) and give me some feedback.

Kind regards

**Comment by sanchr** [comment]
Hi,
first of all, i found the information in the attached document on page 33: "Abweichende Kardinalität 1..1" (Profile EXTENDED).
[8. Factur-X_1.0.07_Technischer-Anhang_Profil_EXTENDED.pdf](https://github.com/user-attachments/files/17615040/8.Factur-X_1.0.07_Technischer-Anhang_Profil_EXTENDED.pdf)

The question is whether the default value should only be set for the EXTENDED profile or also for the other profiles.
The second thing is that I only found an default value in the XRechnung specification 3.0.2, but not in the ZUGFeRD specification.

Thank you very much for your great work!

Kind regards

**Comment by horstoeko** [comment]
Hi @sanchr,

> first of all, i found the information in the attached document on page 33: "Abweichende Kardinalität 1..1" (Profile EXTENDED). [8. Factur-X_1.0.07_Technischer-Anhang_Profil_EXTENDED.pdf](https://github.com/user-attachments/files/17615040/8.Factur-X_1.0.07_Technischer-Anhang_Profil_EXTENDED.pdf)

It does indeed sound to me as you say: apparently this only applies to the EXTENDED profile. In the official examples, however, I can't find any facts/examples where this attribute is set. There does not seem to be a default value (except for XRechnung), which is why it is difficult to define a meaningful default value.

> Thank you very much for your great work!

Much thanks... 

Best regards

**Comment by horstoeko** [comment]
Hi @sanchr,

I've read a little bit...

The BusinessProcessSpecifiedDocumentContextParameter element is required in the “Extended” profile. The Extended profile contains detailed information and is designed for complex business processes where additional information such as the business process context is required. In contrast, this element is not required in the simpler profiles such as Basic or Comfort, as these are intended for standardized, less complex use cases.

I have decided to set a default value for the EXTENDED profile only.

I think that's appropriate. Please give me feedback as soon as possible.

Kind regards

**Comment by sanchr** [comment]
Sounds good to me.
Thanks.

Kind regards
