### ISSUE TITLE
[QUESTION] H68 in pdf_zf_en16931_3.pdf used for water bottles

### ISSUE THREAD

**Issue by DanielRuf** [horstoeko/zugferd#161]
**Your question**
I get `H68` for the water bottles and `C62` for the pledge. But according to sources `C62` is the correct code for "pieces". Or is there something different regarding liquids?

**Sample Code
```
$document->getDocumentPositionQuantity($billedquantity, $billedquantityunitcode, $chargeFreeQuantity, $chargeFreeQuantityunitcode, $packageQuantity, $packageQuantityunitcode);
```

**Comment by horstoeko** [comment]
Hi @DanielRuf,

___C62 (Piece):___ This is the general unit for “piece” and often corresponds to the unit “Stück” or “Einheit” in German. It is a standardized unit that is used when a more specific unit of measure is not required. C62 is often used for counting sizes or individual pieces, i.e. when counting in whole numbers, as with physical products that are counted individually (e.g. 1 table, 5 computers).

___H87 (piece):___ This unit is also used for “piece”, but H87 is specifically defined for the metric system. The main difference is in the specification, as H87 is used more specifically for certain engineering applications where units such as “piece” are required in the context of metric or engineering standards.

Both units appear similar but have different codes, as C62 is intended for general purposes and H87 for specialized technical applications. In practice, they are both translated as “piece”, but it is important to consider the standard and the context of the application when selecting a specific unit.

Kind regards
