### ISSUE TITLE
[QUESTION] incomplete codelist in wiki?

### ISSUE THREAD

**Issue by DanielRuf** [horstoeko/zugferd#162]
**Your question**
It seems the codelist at https://github.com/horstoeko/zugferd/wiki/Codelists is not complete and ends with `G3`.

**Comment by horstoeko** [comment]
Hi @DanielRuf,

I've just noticed the same thing. Apparently GitHub has a size limit when it comes to Markdown. I'll have to find the time to break it down into smaller portions. Alternatively, you can also look in the library under “src/codelists”. I will try to find a solution as soon as possible.

Kind regards
