### ISSUE TITLE
[QUESTION] intentional same alternativecontextparameters for EN 16931 (Comfort)?

### ISSUE THREAD

**Issue by DanielRuf** [horstoeko/zugferd#164]
**Your question**
Not sure if it is intentional, that `contextparameter` and `alternativecontextparameters` is the same (`urn:cen.eu:en16931:2017`) there:

https://github.com/horstoeko/zugferd/blob/master/src/ZugferdProfiles.php#L113-L114

The other profiles do not have the `contextparameter` duplicated in `alternativecontextparameters`.

**Comment by horstoeko** [comment]
Hi @DanielRuf,

You are absolutely right. That was probably a classic copy&paste error. I'll fix it, but I'm not going to make a new release because of this little thing.

Many thanks for the tip and best regards
