### ISSUE TITLE
[BUG] BilledQuantity rounded to 2 decimals

### ISSUE THREAD

**Issue by itbul** [horstoeko/zugferd#165]
When using a BilledQuantity like 1.3412 this is rounded to 2 digits and displayed as 
<ram:BilledQuantity unitCode="C62">1.34</ram:BilledQuantity>

The zugferd format supports up to 4 digits, so this should be shown as 
<ram:BilledQuantity unitCode="C62">1.3412</ram:BilledQuantity>

**Comment by horstoeko** [comment]
Hi @horstoeko,

I see that you haven't had a look at the wiki before. What a pity. Please see the configuration section in our [Wiki](https://github.com/horstoeko/zugferd/wiki/Configuration#general). There is a method in ``ZugferdSettings`` called ``setQuantityDecimals``. 

I hope this helps. 

Kind regards

**Comment by itbul** [comment]
Sorry for that, really missed it.
Thanks for your quick response!
