### ISSUE TITLE
[BUG] ZugferdDocumentReader::firstDocumentPositionAllowanceCharge() wrong pointer valiable name

### ISSUE THREAD

**Issue by pda1986** [horstoeko/zugferd#168]
Hi, I have a problem with this functions:

https://github.com/horstoeko/zugferd/blob/f80505c90b75d993df8fbf84237d4ce7a3773dc0/src/ZugferdDocumentReader.php#L4248
https://github.com/horstoeko/zugferd/blob/f80505c90b75d993df8fbf84237d4ce7a3773dc0/src/ZugferdDocumentReader.php#L4264
https://github.com/horstoeko/zugferd/blob/f80505c90b75d993df8fbf84237d4ce7a3773dc0/src/ZugferdDocumentReader.php#L4351

All of them have wrong code:
`$tradeLineItem = $tradeLineItem[$this->positionPointer];`
Correct code is 
`$tradeLineItem = $tradeLineItem[$this->positionAllowanceChargePointer];`

Same issue have functions:
```
ZugferdDocumentReader::firstDocumentPositionNote()
ZugferdDocumentReader::nextDocumentPositionNote()
ZugferdDocumentReader::getDocumentPositionNote()

ZugferdDocumentReader::firstDocumentPositionAdditionalReferencedDocument()
ZugferdDocumentReader::nextDocumentPositionAdditionalReferencedDocument()
ZugferdDocumentReader::getDocumentPositionAdditionalReferencedDocument()
```
So almost all functions with line
`$tradeLineItem = $tradeLineItem[$this->positionPointer];`
have this issue.

**Comment by horstoeko** [comment]
Hi @pda1986,

no. What you write is wrong. There is no problem with that.

The following code first retrieves the current invoice item that you have set with ``firstDocumentPosition`` and ``nextDocumentPosition``.

```php
$tradeLineItem = $tradeLineItem[$this->positionPointer];
```

The set note or the set surcharge/discount is determined based on this:

```php
$tradeLineItemNote = $this->getObjectHelper()->ensureArray($this->getInvoiceValueByPathFrom($tradeLineItem, "getAssociatedDocumentLineDocument.getIncludedNote", []));
$tradeLineItemNote = $tradeLineItemNote[$this->positionNotePointer];
```
Sorry. Aber ich kann hier keinen Fehler feststellen

**Comment by pda1986** [comment]
Hi @horstoeko , yes you are right there is no issue
Sorry
