### ISSUE TITLE
[QUESTION] getDocumentSellerContact/getDocumentBuyerContact trying to access empty array

### ISSUE THREAD

**Issue by m4tr1ck** [horstoeko/zugferd#171]
**Describe the bug**
Accessing the methods `getDocumentSellerContact` and `getDocumentBuyerContact` from `ZugferdDocumentReader` are throwing `Undefined array key 0`. 
I used the test file `xml_en16931_2.xml` of your test assets.

**To Reproduce**
Use a xml without buyer or seller contact information like the in the test file `xml_en16931_2.xml`.
```PHP
<?php
//... 
$document = ZugferdDocumentReader::readAndGuessFromFile($filename);

$document->getDocumentSellerContact($sellercontactpersonname, $sellercontactdepartmentname, $sellercontactphoneno, $sellercontactfaxno, $sellercontactemailadd);

$document->getDocumentBuyerContact($buyercontactpersonname, $buyercontactdepartmentname, $buyercontactphoneno, $buyercontactfaxno, $buyercontactemailadd);
```

**Expected behavior**
All given variables will be assigned with value `null` based on the given phpdocs and function parameters.

**Screenshots**
![image](https://github.com/user-attachments/assets/e8bdfe7d-8050-4f8a-aead-22f959988cf4)

**Comment by horstoeko** [comment]
Hi @m4tr1ck,

this is not a bug: Please look at the following Excerpts from the code. You did forget to check if a contact exists with ``firstDocumentSellerContact``. You can then continue to check (in a loop) whether other contacts exist with ``nextDocumentSellerContact``:

```php
/**
 * Seek to the first seller contact of the document.
 * Returns true if a first seller contact is available, otherwise false
 * You may use this together with ZugferdDocumentReader::getDocumentSellerContact
 *
 * @return boolean
 */
public function firstDocumentSellerContact(): bool
{
    ... 
}

/**
 * Seek to the next available first seller contact of the document.
 * Returns true if another seller contact is available, otherwise false
 * You may use this together with ZugferdDocumentReader::getDocumentSellerContact
 *
 * @return boolean
 */
public function nextDocumentSellerContact(): bool
{
    ... 
}

/**
 * Get detailed information on the seller's contact person
 *
 * ........
 */
public function getDocumentSellerContact(?string &$contactpersonname, ?string &$contactdepartmentname, ?string &$contactphoneno, ?string &$contactfaxno, ?string &$contactemailadd): ZugferdDocumentReader
{
    ... 
}
```

**Comment by horstoeko** [comment]
Hi @m4tr1ck

everything is documented under [this link](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentReader)

Kind regards

**Comment by m4tr1ck** [comment]
Oh my Bad. 
Thanks you for answering and for the second example. 
I was so into creating into a new template that works with your visualization package that I forgot to look how a function should be used. 

Have a nice day! 

> Hi @m4tr1ck,
> 
> this is not a bug: Please look at the following Excerpts from the code. You did forget to check if a contact exists with ``firstDocumentSellerContact``. You can then continue to check (in a loop) whether other contacts exist with ``nextDocumentSellerContact``:
> 
> ```php
> /**
>  * Seek to the first seller contact of the document.
>  * Returns true if a first seller contact is available, otherwise false
>  * You may use this together with ZugferdDocumentReader::getDocumentSellerContact
>  *
>  * @return boolean
>  */
> public function firstDocumentSellerContact(): bool
> {
>     ... 
> }
> 
> /**
>  * Seek to the next available first seller contact of the document.
>  * Returns true if another seller contact is available, otherwise false
>  * You may use this together with ZugferdDocumentReader::getDocumentSellerContact
>  *
>  * @return boolean
>  */
> public function nextDocumentSellerContact(): bool
> {
>     ... 
> }
> 
> /**
>  * Get detailed information on the seller's contact person
>  *
>  * ........
>  */
> public function getDocumentSellerContact(?string &$contactpersonname, ?string &$contactdepartmentname, ?string &$contactphoneno, ?string &$contactfaxno, ?string &$contactemailadd): ZugferdDocumentReader
> {
>     ... 
> }
> ```

**Comment by horstoeko** [comment]
Hi @m4tr1ck,

> Oh my Bad. Thanks you for answering and for the second example. I was so into creating into a new template that works with your visualization package that I forgot to look how a function should be used.

That is not a problem at all.
 
> Have a nice day!

Have a nice day too.

Kind regards
