### ISSUE TITLE
[QUESTION] Add a discount on the item and a discount on the entire invoice

### ISSUE THREAD

**Issue by VLD-UKRAINE** [horstoeko/zugferd#172]
Hello! Thank you for your work, very useful lib.
I want to add a discount to the items in the invoice and then apply the discount to the entire invoice amount.
I made discount for positions in lines: 
$document->addNewPosition("1")
            ->setDocumentPositionNote("Test zu Zeile 1")
            ->setDocumentPositionProductDetails("Test AG A4", "", "TB100A4")
            ->setDocumentPositionGrossPrice(123.00)
            ->addDocumentPositionAllowanceCharge(14.760, false, 12.00, 123.00, '95', 'Discount')
            ->setDocumentPositionNetPrice(108.24)
            ->setDocumentPositionQuantity(1, "H87")
            ->addDocumentPositionTax('S', 'VAT', 4.500)
            ->setDocumentPositionLineSummation(108.24, 14.76)
            ->addNewPosition("2")
            ->setDocumentPositionNote("Test zu Zeile 2")
            ->setDocumentPositionProductDetails("Joghurt Banane", "", "ARNR2", null, "0160", "4000050986428")
            ->SetDocumentPositionGrossPrice(50.000)
            ->addDocumentPositionAllowanceCharge(5.00, false, 10.00, 50.00, '95', 'Discount')
            ->SetDocumentPositionNetPrice(45.00)
            ->SetDocumentPositionQuantity(5, "H87")
            ->addDocumentPositionTax('S', 'VAT', 4.500)
            ->SetDocumentPositionLineSummation(45.00, 5.00);`

And then I made discount on document level:
 $document->addDocumentTax("S", "VAT", 137.92, 6.20, 4.5);
        $document->addDocumentAllowanceCharge(15.32, false, 'S','VAT',10.00,null,10.00,153.24, null,null,'95','Discount');
        $document->setDocumentSummation(144.12,144.12, 153.24,0.0,15.32,137.92,6.20,null,0.0 );
        
I get a validation error:
Schematron rules for EN16931 (CII): [BR-S-08]-For each different value of VAT category rate (BT-119) where the VAT category code (BT-118) is "Standard rated", the VAT category taxable amount (BT-116) in a VAT breakdown (BG-23) shall equal the sum of Invoice line net amounts (BT-131) plus the sum of document level charge amounts (BT-99) minus the sum of document level allowance amounts (BT-92) where the VAT category code (BT-151, BT-102, BT-95) is "Standard rated" and the VAT rate (BT-152, BT-103, BT-96) equals the VAT category rate (BT-119).
If I made discount in one level (line or document) I can pass validation. 
What methods should I use and how to correctly indicate the discount for such a situation?
P.s. I read your Wiki but it show that the discount is used either at the item level or at the invoice level. No simultaneous use.
Thanks.

**Comment by Marcel-Hartmann** [comment]
I'm working on the Same issue Right now. And my question, regarding This is if we put in Shipping Coast or Document charge amount, or discounts, and These have Tax. Do we Need to add addDocumentLogisticsChargeAmount with the net charge and add the payed tax to the Main document tax and as well in the tax group amount in tax Break down? Tax Setting in TotalTaxAmount? Or can we simple add groß Princes anywhere but did the Numbers fit for the validation rules?
 Normaly i would say we use net pries and add tax to documenta tax regardless which Taxrate and to Toupet of tax breakdown for the group eG 19%.

And help appreshiated!

Bye

**Comment by horstoeko** [comment]
Good morning @VLD-UKRAINE,
Good morning @Marcel-Hartmann,

Thank you very much for your questions. As a first step, I would like to refer you to the corresponding [Wiki article](https://github.com/horstoeko/zugferd/wiki/Creating-XML-Documents#working-with-discounts-and-charges). Please have a look there first. It may answer (at least some of) your questions. We can then clarify the rest here. What would be important for clarification would be an example with concrete case constellations.

Kind regards

**Comment by VLD-UKRAINE** [comment]
Good day @horstoeko 
Thanks for you help. 
I think I found an inaccuracy. Thank you.

**Comment by Marcel-Hartmann** [comment]
Yes thank you very much.
