### ISSUE TITLE
When will zugferd be available for php 8?

### ISSUE THREAD

**Issue by titus-de** [horstoeko/zugferd#175]
**Your question**
When will zugferd be available for php 8? 

**CLI**
composer require horstoeko/zugferd

**response**
Cannot use horstoeko/zugferd v1.0.8 as it requires php ^7 which is not satisfied by your platform.

**Comment by horstoeko** [comment]
Hi @titus-de,

Ich kann dein Problem leide nicht verstehen

![grafik](https://github.com/user-attachments/assets/cf5e1c70-1803-4372-9d9f-be8f3ab7a630)

I can't understand your problem

![grafik](https://github.com/user-attachments/assets/cf3da61b-fc71-4886-9a02-d94846468b07)
