### ISSUE TITLE
Inconsistent Naming in Parameters

### ISSUE THREAD

**Issue by marcelfortmann** [horstoeko/zugferd#177]
https://github.com/horstoeko/zugferd/blob/aee61fe44a29ae5ff95e67f44cb0a9f2b20caf38/src/ZugferdDocumentBuilder.php#L2960

$startdate should be $startDate

**Comment by horstoeko** [comment]
Hi @marcelfortmann,

Thank you very much. Since I don't assume that the world will collapse because of this, I would like to clock this in for the next release.... :-)

Best regards
