### ISSUE TITLE
Not compatible with xrechnung_2.3 and xrechnung_3.0

### ISSUE THREAD

**Issue by martinemmert** [horstoeko/zugferd#18]
Hi there 👋 

First of all - fantastic work. Thank you for building this!
Currently, this library is not up to date with new releases of the specification.
The specs for `xrechnung_2.3` and `xrechnung_3.0` were released by kosit. 

I would love to help, but I need to figure out where to start. Can you point me in the right direction?

**Comment by horstoeko** [comment]
Hi @martinemmert 

Thank you very much for the kind words. I am just back from my summer holiday and need to find out for myself. For some reason, XInvoice 2.3 and XInvoice 3.0. Can you send me some info material on this? I will, however, go in search of information myself - but only when I have arrived here at home again... :-)

Regards

**Comment by horstoeko** [comment]
Hi @martinemmert 

I have now also added support for UniversalCommunication - at the moment only for Seller and Buyer. See Commit [9b4474e](https://github.com/horstoeko/zugferd/commit/9b4474ed8af8d9bd8fef45be4cb150384899941a)

**Comment by horstoeko** [comment]
Hi @martinemmert

I'm closing the ticket. I have made the requested implementations and checked against KosIT's current validator for the validity of the XInvoice 3.0 profile. If something is still missing, I would like to ask you to open a new issue.

**Comment by martinemmert** [comment]
Hey @horstoeko thanks for looking into this that quickly. I am currently occupied and can't continue working on the project where I use this library until mid next week. Will definitely come back with feedback. 👍
