### ISSUE TITLE
[QUESTION] BT-17 Missing ? 

### ISSUE THREAD

**Issue by Disservin** [horstoeko/zugferd#188]
Hi I think `BT-17` might be missing? At least I can't find it when searching for `BT-17` there's only a `BT-X-17` which seems to be something else.

The latest specification says
```
Tender or lot reference BT-17 Document Reference 0..1 19
Die Kennung der Ausschreibung oder des Loses auf die/das sich die Rechnung bezieht
```

`BT-18` as well?

**Comment by horstoeko** [comment]
Hi @Disservin,

this is little bit tricky... It is declared as an additional referenced document. See this:

![image](https://github.com/user-attachments/assets/19edf7f8-2a41-4d91-8118-abb28670fa95)

You have to use TypeCode "50":

![image](https://github.com/user-attachments/assets/aa28a898-731e-445a-b049-30693a50d9e7)

Kind regards

**Comment by Disservin** [comment]
@horstoeko I am not entirely sure I understand that sorry :) I am not sure which function I should use to add this for an XRechnung Invoice?

**Comment by Disservin** [comment]
I see it being referenced in the `addDocumentAdditionalReferencedDocument` function but I am bit confused why there it is annotated as `__BT-122`

**Comment by horstoeko** [comment]
Hi @Disservin,

That is correct. The method ``addDocumentAdditionalReferencedDocument`` is your friend... :-) I'll probably have to improve the documentation a bit, but to make you believe me, here is the excerpt from the official documentation...

__BT-122__

![image](https://github.com/user-attachments/assets/5d3c7760-b9c9-478f-80c9-aa4ecebcde1e)

__BT-17__

![image](https://github.com/user-attachments/assets/16a0ffc1-bd81-46aa-8575-65bb3e3d9814)

__BT-18__

![image](https://github.com/user-attachments/assets/1a4ae620-5496-4f2f-93bf-c992611b5726)

Kind regards

**Comment by Disservin** [comment]
Can you share that document link with me ? I've only ever found one from the itplr-kosit which looks different?

**Comment by horstoeko** [comment]
Hi @Disservin,

You can go to https://www.ferd-net.de/standards/zugferd-2.3.2/zugferd-2.3.2.html and register there free of charge. You will then be offered the download. Another advantage: You can be informed about new features.
