### ISSUE TITLE
[FEATURE] Allow adding empty ShipTo nodes to the document without enforcing a TradeParty name

### ISSUE THREAD

**Issue by martinemmert** [horstoeko/zugferd#189]
**Describe the feature**

This Issue is a follow-up to #101 

I want to create an invoice with a tax exemption for intra-community supply.
The business rule BR-IC-12 states that, therefore, the country code of the ship to address (BT-80) must be set in `/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeDelivery/ram:ShipToTradeParty/ram:PostalTradeAddress/ram:CountryID`

The method `setDocumentShipTo` forces me to provide a name of the `ShipToTradeParty`. 
However, according to the ZUGFeRD and X-Rechnung specifications, these fields shall be used if the name is not equal to the buyer's name.

> Das Informationselement ist zu verwenden, wenn der Empfänger vom Erwerber abweicht.
> _X-Rechnung Spec_

> Shall be used if the Deliver to party is different from the Buyer.
> _Factur-X Spec_

**Expected behavior**

Provide a method like `setDocumentShipToAddress` that uses an empty TradeParty if `getShipToTradeParty` returns `null`.

See `src/ZugferdDocumentBuilder.php:1016`

**Additional context**
We could work around this by providing the same name as the buyer.
It might be possible that we get a validation error then.

**Comment by horstoeko** [comment]
Hi @martinemmert,

thank you for you contribution. But I understand BT-70 differently. There it is written: “must be used if the recipient of the goods or services is not identical with the buyer”, but for me this means in reverse: “___can___ be used if the recipient of the goods or services is identical with the buyer”. Unfortunately, I cannot find a validation rule for this either. Have you checked it with a validator of your choice?

Please give me feedback.

Kind regards

**Comment by horstoeko** [comment]
Hi @martinemmert,

> May I ask why the name for a TradingParty is required? Is that due to some structural reason, or was that based on a decision to simplify your workload?

For some parties (e.g. SellerTradeParty), the name is indeed mandatory. However, as all parties use the same underlying data type (``TradePartyType``), it is difficult to differentiate between them for the specific use case. But I want to see what I can do.

> Based on the current findings, I'd prioritize this feature as low.

Okay. I will think about it anyway... ;-)

> Cheers, and thanks for your fantastic work here!

Thank you.

Kind regards

**Comment by horstoeko** [comment]
Hi @martinemmert,

I thing I have found a solution - please have a look at [this commit](https://github.com/horstoeko/zugferd/commit/380709c89ba285db8f4da3535316caeb477a2afc)

Kind regards

**Comment by martinemmert** [comment]
Thanks for the fast resolution here! Your solution looks reasonable and might just what was needed here :)
