### ISSUE TITLE
[BUG] No mimetype found when uppercase filename

### ISSUE THREAD

**Issue by stear01** [horstoeko/zugferd#196]
- [x] I have read the [documentation](https://github.com/horstoeko/zugferd/wiki) and could not find a solution to my issue.
- [x] I have searched open and closed [issues](https://github.com/horstoeko/zugferd/issues) to ensure my issue has not already been reported.

**Describe the bug**

Method `ZugferdDocumentPdfBuilderAbstract::attachAdditionalFileByContent` and `ZugferdDocumentPdfBuilderAbstract::attachAdditionalFileByRealFile` throw `ZugferdUnknownMimetype` exception when the filename extension has uppercase character.

```
$merger = new ZugferdDocumentPdfMerger($xmlContent, $pdfContent);
$merger->attachAdditionalFileByContent('Sample content', 'test.TXT'); // Error
$merger->attachAdditionalFileByContent('Sample content', 'test.txt'); // Works
```

The MimeDb should lowercase the extension and alternatively, we could also pass our own mime type instead and use the MimeDb guesser if empty.

```
public function attachAdditionalFileByContent(string $content, string $filename, string $displayName = "", string $relationshipType = "", string $mimeType = "")
```

**Comment by horstoeko** [comment]
Hi,

Actually, the issue is not correctly placed here. But I will take care of it anyway. 

Many thanks and best regards

**Comment by horstoeko** [comment]
Hi @stear01,

I've made a fix in [horstoeko/mimedb](https://github.com/horstoeko/mimedb). Please update your dependencies.

Kind regards
