### ISSUE TITLE
[BUG] Merged PDFs are not PDF/A-3 compliant

### ISSUE THREAD

**Issue by wurst-hans** [horstoeko/zugferd#197]
I'm using a common PDF file created by my custom invoice tool and embed an XRechnung using your library. This works so far and I can see the embedded XML using a standard PDF viewer.
But when trying to validate this ZUGFeRD document with latest validator from Mustangproject, the document gets rejected because it's not compliant to PDF/A-3. Using veraPDF to double-check the validation result, I get the following errors:

```
Validation Report
File:	xxx
Validation Profile:	PDF/A-3B validation profile
Compliance:	Failed

Statistics
Version:	1.26.2
Parser:	GreenField
Build Date:	2024-05-19T13:33:00+02:00
Processing time:	00:00:00.699
Total rules in Profile:	145
Passed Checks:	6635
Failed Checks:	2

Validation information
Specification: ISO 19005-3:2012, Clause: 6.2.11.4.1, Test number: 1	
The font programs for all fonts used for rendering within a conforming file shall be embedded within that file, as defined in ISO 32000-1:2008, 9.9
PDFont	
Subtype == "Type3" || Subtype == "Type0" || renderingMode == 3 || fontFile_size == 1	
root/document[0]/pages[0](3 0 obj PDPage)/contentStream[0](4 0 obj PDContentStream)/operators[9]/xObject[0]/contentStream[0](5 0 obj PDContentStream)/operators[18]/font[0](Helvetica)
The font program is not embedded


Specification: ISO 19005-3:2012, Clause: 6.1.2, Test number: 2	
The aforementioned EOL marker shall be immediately followed by a % (25h) character followed by at least four bytes, each of whose encoded byte values shall have a decimal value greater than 127
CosDocument	
headerByte1 > 127 && headerByte2 > 127 && headerByte3 > 127 && headerByte4 > 127	
root
Binary comment in the file header is missing or does not start with 4 bytes with byte values above 127 (first four bytes = 139, 250, 0, 174)
```

I assume, such a ZUGFeRD will be rejected by clients, when they use validator from Mustangproject too.

**Comment by horstoeko** [comment]
Hi  @wurst-hans,

I can't see any errors... And so far no one has had a problem. I don't know how I can help you. The PDF issue is also only solved by another library. Please contact them perhaps unter https://github.com/Setasign/FPDF.

Incidentally, I tried this myself once: (I used the example En16931SimpleWithPdf.php)

![grafik](https://github.com/user-attachments/assets/8f8c32bc-0721-4571-8e8d-2d814e3bc591)
