### ISSUE TITLE
[CANT REPRO] simplexml_load_file failing to load external entity

### ISSUE THREAD

**Issue by andreas-p** [horstoeko/zugferd#198]
I'm running php8.2-fpm on Debian12, and found that merging PDFs will fail in ZugferdDocumentPdfBuilderAbstract.php:439

`$xmp = simplexml_load_file(ZugferdSettings::getFullXmpMetaDataFilename());`

When trying to load assets/facturx_extension_schema.xmp, simple_load_file will throw "failed to load external entity". The problem persists even when copying the file to /tmp/facturx_extension_schema.xmp and trying to load from there. Apparently, php-fpm is getting confused in this case, where the php files are located on a mounted drive (just a guess).
When using CLI, simplexml_load_file will work just fine.

My simple workaround is to use
`$xmp = simplexml_load_string(file_get_contents(ZugferdSettings::getFullXmpMetaDataFilename()));`

**Comment by horstoeko** [comment]
Hi @andreas-p,

Sorry, but I can't accept this as a bug report. There are unit tests that automatically test the entire system. If this was a bug, then we wouldn't have successful builds. Since I have no idea what you are doing, I have to close the issue.

Kind regards
