### ISSUE TITLE
[QUESTION] testing with php-fpm

### ISSUE THREAD

**Issue by andreas-p** [horstoeko/zugferd#199]
Is the project tested with php-fpm or php-cli only?

As mentioned in #198, I had issues with simplexml_load_file in php-fpm. I certainly would expect that this function works similar in php-fpm and php-cli, but it obviously doesn't.

**Comment by andreas-p** [comment]
Apparently, it's not php-fpm alone. simple_load_file executed in a simple test.php works fine, but not when used in a Nextcloud application.

**Comment by horstoeko** [comment]
Hi @andreas-p,

OK. But how can I help? It doesn't seem to be a problem with my library. I'm going to close the issue as I can't offer any help in this regard.

Kind regards.
