### ISSUE TITLE
[QUESTION] Validation Error [BR-DE-23-a] Wenn BT-81 "Payment means type code" einen Schlüssel für Überweisungen enthält (30, 58), muss BG-17 "CREDIT TRANSFER" übermittelt werden.

### ISSUE THREAD

**Issue by Christian-Rinne** [horstoeko/zugferd#200]
Hallo,

erstmal vielen Dank für dieses tolle Package!

als ich habe folgendes Problem, wenn ich mein E-Rechnung durch diverse Online-Validatoren schicke erhalte ich immer:

```
[BR-DE-23-a] Wenn BT-81 "Payment means type code" einen Schlüssel für Überweisungen enthält (30, 58), muss BG-17 "CREDIT TRANSFER" übermittelt werden.
```

mein Code dazu sieht so aus:

```php
    private function setDocumentPaymentInformation()
    {
        $this->document = $this->document
            ->addDocumentPaymentTerm($this->order->payment_text)
            ->addDocumentPaymentMean(30)
            ->addDocumentPaymentMeanToCreditTransfer(
                str_replace(' ', '', $this->seller->user_account_iban),
                (!empty($this->seller->user_company) ? $this->seller->user_company : $this->seller->user_firstname.' '.$this->seller->user_lastname),
                null,
                $this->seller->user_account_bic,
                $this->order->invoice_nr
            );
    }
```

Die Felder haben alle korrekte Werte. IBAN und Bic werden aber doch auch nicht auf Syntax überprüft oder?

Wie gebe ich denn CREDIT TRANSFER an, wenn nicht mit addDocumentPaymentMeanToCreditTransfer() ?

Ich benutze Version 1.0.90 von horstoeko/zugferd

**Comment by Christian-Rinne** [comment]
thank you very much for your incredible fast help!

**Comment by horstoeko** [comment]
Hi @Christian-Rinne,

No problem. Has it worked for you so far?

**Comment by horstoeko** [comment]
Hi @Christian-Rinne,

in the new release 1.0.91 I have added two new shorthand-methods `addDocumentPaymentMeanToCreditTransferNonSepa `and `addDocumentPaymentMeanToDirectDebitNonSepa `to ZugferdDocumentBuilder.

Kind regards

**Comment by Christian-Rinne** [comment]
@horstoeko 
It worked perfectly - thank you so much!  
Once I’ve completed the implementation, I’d like to make a small donation as a token of appreciation. Could you let me know how I can do that?
