### ISSUE TITLE
Consistency of generated Zugferd PDF files

### ISSUE THREAD

**Issue by Disservin** [horstoeko/zugferd#201]
Hi, 

I've noticed two features in the zugferd PDF creation that make it difficult to achieve deterministic output:

1. Random bits are being added here: https://github.com/horstoeko/zugferd/blob/master/src/ZugferdPdfWriter.php#L97
What's the purpose of this randomization?

2. Are the ModifyDate/CreationDate fields strictly required by the specification?

Context: I'm trying to write unit tests where input files A & B should consistently produce the same output PDF C. The random bits and timestamps make this challenging. While timestamps could potentially be handled by mocking system time, this feels like a hacky solution.

**Comment by Disservin** [comment]
& do we really need the `/ID` trailer ? `Encrypt` isn't even given?

**Comment by horstoeko** [comment]
Hi!

Unfortunately, I don't understand the question because I can't see the problem you seem to have with it either. How can I help you? The implementation works. So I don't know what's bothering you?

Kind regards?

**Comment by Disservin** [comment]
Well, automated testing becomes difficult...

Non-deterministic PDF generation significantly complicates testing.
In unit tests, you often validate PDF generation by comparing file content with a known good reference document. However, since identical inputs produce different binary outputs, simple validations like diff file1 file2 or checksum comparisons fail.

This kinda forces you to:

1. Extract and validate the XML separately
2. Use some PDF parsing tool to skip the non deterministic output, to verify the human readable content
3. Overall more complex test assertions

It makes testing more complex and time consuming, especially if you treat this as a blackbox test. Simple assertions like "given these inputs, the output should exactly match this reference file" become impossible.

> In a PDF document, the random bytes after the PDF version are not a mandatory technical requirement, but a common practice to support certain compatibility and security aspects.

First time that I'm hearing about this, do you have any reference for this?

> And you are right: Neither CreateDate nor ModifyDate are defined as mandatory fields in the PDF standard. They are part of the optional information dictionary, which can contain metadata such as title, author, keywords, etc. However, I will not remove this information as it is useful for the recipient of such an e-invoice for user and archiving purposes.

Maybe make those optional fields optional for a user who's consuming this library too?

**Comment by PurHur** [comment]
+1 for deterministic Testing. In the near future i will build the same as disservin does here for us. We absolutly need to ensure the viewable PDF is the same as the XML.

**Comment by horstoeko** [comment]
Hi,

but I can't change an existing implementation just so that your unit tests go through.

Kind regards

**Comment by Disservin** [comment]
This has like no breaking changes though ? The random bytes are random and aren't used for anything. It makes no difference if they are not random?
The timestamps can be optionally disabled.

**Comment by horstoeko** [comment]
Unfortunately, I find it a little disrespectful the way you are hammering me here. I develop and maintain the library in my spare time - and I love doing it. Perhaps a small thank you would have been appropriate at the beginning. I want to see what I can do for you. At the moment I'm very tied up with my “real” job.

Kind regards

**Comment by Disservin** [comment]
I wasn't trying to hammer you into anything - I simply wanted to understand the technical reasoning for these things and if you were open for changes. As someone who maintains open source software myself, I appreciate your work on this library. 

I'd be happy to implement this myself if you'll approve the general direction of these changes.

**Comment by horstoeko** [comment]
Hi @Disservin,
Hi @PurHur,

Of course I am open to changes - no question. But because this library is already quite widespread and widely used, I have to make sure that I don't make any changes that I'll regret at some point. As I said: I want to see what I can do for you. If you like, you are very welcome to submit a PR.

Kind regards

**Comment by horstoeko** [comment]
Hi @Disservin,
Hi @PurHur,

I have created a PR #203 and tried to meet your requirements. I ask you for a review and feedback.

Thank you very much and have a nice weekend.

**Comment by Disservin** [comment]
This looks good from a consistency standpoint (which this issue was about) I think, thank you.  
Though I'd like to say that the benefit of having it be deterministic is not solely beneficial for testing as stated in the variable comment
> this mode should only be used for testing purposes

**Comment by horstoeko** [comment]
Hi @Disservin,

Okay. Thanks for the feedback. I would then transfer this to the productive branch and am pleased to have satisfied you with it.

>Though I'd like to say that the benefit of having it be deterministic is not solely beneficial for testing as stated in the variable comment

I don't think so. This metadata has made sense for decades and therefore has a right to exist... ;-)

Kind regards
