### ISSUE TITLE
[QUESTION] Translation of validation errors

### ISSUE THREAD

**Issue by VLD-UKRAINE** [horstoeko/zugferd#204]
Hello,
Is it possible to enable translation of validation errors into other languages (besides English), for example, into German?
Thanks.

**Comment by horstoeko** [comment]
Hi @VLD-UKRAINE,

At the moment this is not planned. I'll add it to the roadmap.

Best regards

**Comment by horstoeko** [comment]
HI @VLD-UKRAINE,

so that I can assess this correctly, it would be very nice of you to tell me specifically what you mean by “validation errors”? 

Best regards

**Comment by VLD-UKRAINE** [comment]
Hi @horstoeko. Thanks for your answer. 
After generating the electronic invoice, I validate it with the Kosit validator (ZugferdKositValidator). Sometimes, if something is wrong, the validator returns errors, for example: 
1: Validation error. One ore more files were rejected
2: Schematron rules for EN16931 (CII): [BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).
Errors are only in English. I would like to be able to change the language in which errors are displayed.
Best regards, Vlad.

**Comment by horstoeko** [comment]
Hi @VLD-UKRAINE,

Messages as described by you in point 2 are generated by the external Java application. They may be able to help you [there](https://github.com/itplr-kosit/validator). The message from point 1 does indeed come from my library. I cannot offer a translation functionality for this at the moment.

Kind regards
