### ISSUE TITLE
Specify the performance period, which is defined by a start date and an end date

### ISSUE THREAD

**Issue by it-pioneers** [horstoeko/zugferd#205]
Hi all!

My question:
I want to specify a performance period with a start and an end date e.g. for monthly or yearly invoices, how can I do this?
This option should be possible with ZUGFeRD version 2 but it does not seem to be implemented. Can this be implemented in the short term?

Thank you,
Boris

**Comment by horstoeko** [comment]
Hi @it-pioneers,

thank you for the question. Did you read the class documentation for the `ZugferdDocumentBuilder` in our [Wiki](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder). The are the following methods available:

* [setDocumentBillingPeriod](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentbillingperiod)
* [setDocumentPositionBillingPeriod](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentpositionbillingperiod)

Maybe this is what you are looking for...

Kind regards

**Comment by it-pioneers** [comment]
This solves my problem with the billing period but not with the delivery period. Is there a function for that too?

Thanks!

**Comment by horstoeko** [comment]
HI @it-pioneers,

There are no explicit fields for a delivery period in the ZUGFeRD/Factur-X standard. Workarounds such as the use of free text fields or user-defined extensions in the extended profile are possible approaches if such information is required. The specific requirements should be implemented in consultation with business partners and software providers.

However, it is possible to specify a delivery time:

* [setDocumentSupplyChainEvent](https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentsupplychainevent)
* [setDocumentPositionSupplyChainEvent]( https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentpositionsupplychainevent)

Kind regards
