### ISSUE TITLE
[BUG] function toDateTime returns DateTime|null but DateTime::createFromFormat could return DateTime|false ...

### ISSUE THREAD

**Issue by rycks** [horstoeko/zugferd#206]
Hello Daniel,
there is a little bug today into parsing XML with your great lib ...

```
  <ram:IssueDateTime>
    <udt:DateTimeString format="102">
      20241011
    </udt:DateTimeString>
  </ram:IssueDateTime>
```

Then in that race condition i have that error

```
Return value of horstoeko\zugferd\ZugferdObjectHelper::toDateTime() must be an instance of DateTime or null, bool returned
```

cheers
(Éric from France)

**Comment by rycks** [comment]
First fix was to trim dateTimeString

**Comment by horstoeko** [comment]
Hi @rycks,

nice to hear/read from you again... :-) 

I have seen your problem. Unfortunately, with the best will in the world, I can imagine that this is a direct bug in my library. At the moment I have no idea either. I am almost afraid that this is a problem with the engine that is responsible for serialization/deserialization.

Kind regards

**Comment by rycks** [comment]
:-(

as a maybe new test case to cover your code, please move this xml_basic_1.txt to tests/assets/xml_basic_1.xml then start phpunit tests ... it will fail on parsing date value like i have with the invoice of one of my supplier

[xml_basic_1.txt](https://github.com/user-attachments/files/18060683/xml_basic_1.txt)

**Comment by horstoeko** [comment]
Hi @rycks,

That's really exciting. I believe you. However, I wonder what the deserializer is doing there. I'll have a look at your quick fix tonight. 

Thank you very much for the tip.

**Comment by horstoeko** [comment]
Hi @rycks,

I checked this and also wrote a special test for it. I was actually able to understand it. I'll finish a fix for it. This fix will come with the next release.

Thank you very much @rycks :-)

**Comment by rycks** [comment]
hey @horstoeko , it's already tonight now in your country ?-)

your are really incredible ! thanks for your so beautiful source code, i'm dreamin' "one day i will code as horstoeko"
