### ISSUE TITLE
Unable to find PDF file header.

### ISSUE THREAD

**Issue by SMEWebify** [horstoeko/zugferd#21]
Hello

I try to use the package, but I get an error:

> setasign \ Fpdi \ PdfParser\
> PdfParserException
> PHP 8.1.8
> 9.52.15
> Unable to find PDF file header.

- I copied and pasted the example En16931SimpleWithPdf.php and include this in my controller

- I have an error in my terminal

> Undefined method 'generateDocument'.
> Undefined method 'saveDocument'.

- However, I have the use of classes

```
use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdDocumentPdfBuilder;
use horstoeko\zugferd\ZugferdProfiles;
use horstoeko\zugferd\codelists\ZugferdPaymentMeans;
```

- what my composer.json includes

```
    "require": {
        "php": "^8.0.2",
        "barryvdh/laravel-dompdf": "2.0.0",
       [...]
        "horstoeko/zugferd":"^1",
        "setasign/fpdf": "^1.8",
        "setasign/fpdi": "^2.3"
    },
```

did I miss something?

Regards

Kévin

**Comment by horstoeko** [comment]
Hi @SMEWebify ,

Can you attach the Code you use to the issue?

Thanks

**Comment by SMEWebify** [comment]
Hi @horstoeko 

thank you for your reply

```php

<?php

namespace App\Http\Controllers;


use PDF;

use DateTime;
use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdDocumentPdfBuilder;
use horstoeko\zugferd\ZugferdProfiles;
use horstoeko\zugferd\codelists\ZugferdPaymentMeans;

class PrintController extends Controller
{
    
    public function getInvoiceFactureX(Invoices $Document)
    {

        $document = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_EN16931);
        $document
            ->setDocumentInformation("471102", "380", \DateTime::createFromFormat("Ymd", "20180305"), "EUR")
            ->addDocumentNote('Rechnung gemäß Bestellung vom 01.03.2018.')
            ->addDocumentNote('Lieferant GmbH' . PHP_EOL . 'Lieferantenstraße 20' . PHP_EOL . '80333 München' . PHP_EOL . 'Deutschland' . PHP_EOL . 'Geschäftsführer: Hans Muster' . PHP_EOL . 'Handelsregisternummer: H A 123' . PHP_EOL . PHP_EOL, null, 'REG')
            ->setDocumentSupplyChainEvent(\DateTime::createFromFormat('Ymd', '20180305'))
            ->addDocumentPaymentMean(ZugferdPaymentMeans::UNTDID_4461_58, null, null, null, null, null, "DE12500105170648489890", null, null, null)
            ->setDocumentSeller("Lieferant GmbH", "549910")
            ->addDocumentSellerGlobalId("4000001123452", "0088")
            ->addDocumentSellerTaxRegistration("FC", "201/113/40209")
            ->addDocumentSellerTaxRegistration("VA", "DE123456789")
            ->setDocumentSellerAddress("Lieferantenstraße 20", "", "", "80333", "München", "DE")
            ->setDocumentSellerContact("Heinz Mükker", "Buchhaltung", "+49-111-2222222", "+49-111-3333333","info@lieferant.de")
            ->setDocumentBuyer("Kunden AG Mitte", "GE2020211")
            ->setDocumentBuyerReference("34676-342323")
            ->setDocumentBuyerAddress("Kundenstraße 15", "", "", "69876", "Frankfurt", "DE")
            ->addDocumentTax("S", "VAT", 275.0, 19.25, 7.0)
            ->addDocumentTax("S", "VAT", 198.0, 37.62, 19.0)
            ->setDocumentSummation(529.87, 529.87, 473.00, 0.0, 0.0, 473.00, 56.87, null, 0.0)
            ->addDocumentPaymentTerm("Zahlbar innerhalb 30 Tagen netto bis 04.04.2018, 3% Skonto innerhalb 10 Tagen bis 15.03.2018")
            ->addNewPosition("1")
            ->setDocumentPositionProductDetails("Trennblätter A4", "", "TB100A4", null, "0160", "4012345001235")
            ->setDocumentPositionGrossPrice(9.9000)
            ->setDocumentPositionNetPrice(9.9000)
            ->setDocumentPositionQuantity(20, "H87")
            ->addDocumentPositionTax('S', 'VAT', 19)
            ->setDocumentPositionLineSummation(198.0)
            ->addNewPosition("2")
            ->setDocumentPositionProductDetails("Joghurt Banane", "", "ARNR2", null, "0160", "4000050986428")
            ->SetDocumentPositionGrossPrice(5.5000)
            ->SetDocumentPositionNetPrice(5.5000)
            ->SetDocumentPositionQuantity(50, "H87")
            ->AddDocumentPositionTax('S', 'VAT', 7)
            ->SetDocumentPositionLineSummation(275.0);
        
            $pdf = new ZugferdDocumentPdfBuilder($document, dirname(__FILE__) . "/emptypdf.pdf");
            $pdf->generateDocument();
            $pdf->saveDocument(dirname(__FILE__) . "/fullpdf.pdf");
    }
}

```

Maybe it's the dirname(__FILE__) that is not able to create?

(Ps the scipt for creating an XML file is functional)

**Comment by horstoeko** [comment]
Hi @SMEWebify,

thank you for your answer. The ```__FILE__``` Variable is the directory of you current php script. Your current script is the file where ```PrintController```-Class is located. This will probably be somewhere under \ApplicationHttp\Controllers. The PDF should be there. However, there is probably no emptypdf.pdf file there.

**Comment by SMEWebify** [comment]
I confirm, there is nothing

If it helps, error log

![image](https://github.com/horstoeko/zugferd/assets/75578469/aa334952-ece4-4cec-912e-8ee74cf47ed9)
![image](https://github.com/horstoeko/zugferd/assets/75578469/015482f3-b53d-4f07-9465-bfd1c2dd54e4)
![image](https://github.com/horstoeko/zugferd/assets/75578469/b9e9108d-17a7-4cad-9425-6da38d10aff9)
![image](https://github.com/horstoeko/zugferd/assets/75578469/81851161-32c2-45bf-9371-3dd208758519)
![image](https://github.com/horstoeko/zugferd/assets/75578469/dab7f3e5-1099-42f5-b906-a9a8578f9cf4)
![image](https://github.com/horstoeko/zugferd/assets/75578469/6ffd1ebd-1327-41ac-9bab-e16b4f721217)
![image](https://github.com/horstoeko/zugferd/assets/75578469/a6de9a64-8a1c-4f95-8668-98a0d50b57c8)

**Comment by horstoeko** [comment]
Hi  @SMEWebify ,

Please tell me how I can help you. All you have to do is make sure that the constructur of the class ```ZugferdDocumentPdfBuilder``` is passed a valid PDF file or PDF data as a string. I'm afraid I'm at a bit of a loss as to how to help you, which of course I'd like to do.

**Comment by horstoeko** [comment]
Hi @SMEWebify  

No Problem. Gladly again at any time. 

Regards

**Comment by ajaxvador** [comment]
> @horstoeko Je viens de me rendre compte de mon erreur, c'est bon, merci pour votre temps et votre retour rapide. Super forfait

I have the same problem but can't find a solution 

use horstoeko\zugferd\ZugferdDocumentBuilder;
use horstoeko\zugferd\ZugferdDocumentPdfBuilder;
use horstoeko\zugferd\ZugferdProfiles;
use horstoeko\zugferd\codelists\ZugferdPaymentMeans;

 $document = ZugferdDocumentBuilder::CreateNew(ZugferdProfiles::PROFILE_EN16931);
        $document
            ->setDocumentInformation("471102", "380", \DateTime::createFromFormat("Ymd", "20180305"), "EUR")
            ->addDocumentNote('Rechnung gemäß Bestellung vom 01.03.2018.')
            ->addDocumentNote('Lieferant GmbH' . PHP_EOL . 'Lieferantenstraße 20' . PHP_EOL . '80333 München' . PHP_EOL . 'Deutschland' . PHP_EOL . 'Geschäftsführer: Hans Muster' . PHP_EOL . 'Handelsregisternummer: H A 123' . PHP_EOL . PHP_EOL, null, 'REG')
            ->setDocumentSupplyChainEvent(\DateTime::createFromFormat('Ymd', '20180305'))
            ->addDocumentPaymentMean(ZugferdPaymentMeans::UNTDID_4461_58, null, null, null, null, null, "DE12500105170648489890", null, null, null)
            ->setDocumentSeller("Lieferant GmbH", "549910")
            ->addDocumentSellerGlobalId("4000001123452", "0088")
            ->addDocumentSellerTaxRegistration("FC", "201/113/40209")
            ->addDocumentSellerTaxRegistration("VA", "DE123456789")
            ->setDocumentSellerAddress("Lieferantenstraße 20", "", "", "80333", "München", "DE")
            ->setDocumentSellerContact("Heinz Mükker", "Buchhaltung", "+49-111-2222222", "+49-111-3333333","info@lieferant.de")
            ->setDocumentBuyer("Kunden AG Mitte", "GE2020211")
            ->setDocumentBuyerReference("34676-342323")
            ->setDocumentBuyerAddress("Kundenstraße 15", "", "", "69876", "Frankfurt", "DE")
            ->addDocumentTax("S", "VAT", 275.0, 19.25, 7.0)
            ->addDocumentTax("S", "VAT", 198.0, 37.62, 19.0)
            ->setDocumentSummation(529.87, 529.87, 473.00, 0.0, 0.0, 473.00, 56.87, null, 0.0)
            ->addDocumentPaymentTerm("Zahlbar innerhalb 30 Tagen netto bis 04.04.2018, 3% Skonto innerhalb 10 Tagen bis 15.03.2018")
            ->addNewPosition("1")
            ->setDocumentPositionProductDetails("Trennblätter A4", "", "TB100A4", null, "0160", "4012345001235")
            ->setDocumentPositionGrossPrice(9.9000)
            ->setDocumentPositionNetPrice(9.9000)
            ->setDocumentPositionQuantity(20, "H87")
            ->addDocumentPositionTax('S', 'VAT', 19)
            ->setDocumentPositionLineSummation(198.0)
            ->addNewPosition("2")
            ->setDocumentPositionProductDetails("Joghurt Banane", "", "ARNR2", null, "0160", "4000050986428")
            ->SetDocumentPositionGrossPrice(5.5000)
            ->SetDocumentPositionNetPrice(5.5000)
            ->SetDocumentPositionQuantity(50, "H87")
            ->AddDocumentPositionTax('S', 'VAT', 7)
            ->SetDocumentPositionLineSummation(275.0);
        
            $pdf = new ZugferdDocumentPdfBuilder($document, dirname(__FILE__) . "/emptypdf.pdf");
            $pdf->generateDocument();
            $pdf->saveDocument(dirname(__FILE__) . "/fullpdf.pdf");

        }
     
        $this->streamReader->reset(0);
        $maxIterations = 1000;
    //    dd(  $this->fileHeader);
        while (true) {
            $buffer = $this->streamReader->getBuffer(false);
            $offset = \strpos($buffer, '%PDF-');
            if ($offset === false) {
                if (!$this->streamReader->increaseLength(100) || (--$maxIterations === 0)) {
                    throw new PdfParserException(
                        'Unable to find PDF file header.',
                        PdfParserException::FILE_HEADER_NOT_FOUND
                    );
                }
                continue;
            }
            break;
        }
 
        $this->fileHeaderOffset = $offset;
        $this->streamReader->setOffset($offset);
 
        $this->fileHeader = \trim($this->streamReader->readLine());
        return $this->fileHeaderOffset;
    }
 
    /**
     * Get the cross-reference instance.
     *
     * @return CrossReference
**Arguments
"Unable to find PDF file header."**

How did you solve the problem?  
Thanks for your help
