### ISSUE TITLE
Significantly increased PDF file size after merging XML and PDF

### ISSUE THREAD

**Issue by IgitBuh** [horstoeko/zugferd#211]
First of all, please allow me to express my sincere gratitude for your work. Thank you very much!

**Your question**
I've been using tFPDF for a long time now and I would like to continue using it.
To meet the new tax requirements, I would like to use your library to create the required XML and merge it with my PDF invoices.
I have implemented your basic sample code and the XML creation works fine and is valid.
I have then merged it with my PDF and although it works as well, I am very confused about the resulting file size.

The original PDF is 52 KB.
The sample XML is about 1 KB.
The merged ZUGFeRD PDF from these two files is 116 KB.

Is this normal? This seems to be a huge overhead. Would it be possible to keep the file size at a minimum? I would expect the result to be 53 KB, but even with some additional header data not larger than 60 KB.

**Sample Code**

```
    $pdf_string = $pdf->Output($outFileName,'S');
    $pdfMerger = new ZugferdDocumentPdfMerger($xml, $pdf_string);
    $pdfMerger->generateDocument();
    $pdfFileStream = $pdfMerger->downloadString($outFileName);
```

**Comment by horstoeko** [comment]
Good morning @IgitBuh,

> First of all, please allow me to express my sincere gratitude for your work. Thank you very much!

Thank you very much for the kind words and the appreciation.

> I have then merged it with my PDF and although it works as well, I am very confused about the resulting file size.

I will look into this. Stay tuned.. ;-)

Kind regards

**Comment by horstoeko** [comment]
Hi @IgitBuh,

I have found the problem: The embedded ICC profile was a bit large at 60KB... :-) I switched to a smaller profile by default.

Kind regards
