### ISSUE TITLE
[QUESTION] Notice Error at merging pdf&xml

### ISSUE THREAD

**Issue by jumpski** [horstoeko/zugferd#214]
Error: Notice: Undefined property: horstoeko\zugferd\ZugferdPdfWriter::$PDFVersion
Symfony: 5.4
PHP: 7.4
zugferd: 1.0.95

If i try to merge/build a pdf with xml attached, i get a error: Notice: Undefined property: horstoeko\zugferd\ZugferdPdfWriter::$PDFVersion. It doesnt matte if i use example files or own created files

`$documentPdfBuilder = new ZugferdDocumentPdfBuilder($xmlContent, '/var/www/var/files/documents/invoices/emptypdf.pdf');
        $documentPdfBuilder
            ->setAttachmentRelationshipType('Alternative')
            ->generateDocument()
            ->saveDocument($mergeToPdf);`
or
`(new ZugferdDocumentPdfMerger($xmlContent->getContent(), 'emptypdf.pdf'))->setAdditionalCreatorTool('Contoso ERP 1.0')->generateDocument()->saveDocument($mergeToPdf); ` 

   
![image](https://github.com/user-attachments/assets/5287869e-1b5e-4ea2-a2c8-ad799ae40b06)

![image](https://github.com/user-attachments/assets/368e30fd-3a85-4e9d-91c4-f7613ab3c327)

**Comment by horstoeko** [comment]
Hi @jumpski,

Unfortunately, I cannot reproduce/reconstruct the problem. Everything works perfectly. Perhaps another participant can help?

Kind regards

**Comment by horstoeko** [comment]
Good morning @jumpski,

I took another look this morning: The problem you describe is not a problem with my library. I use external libraries called ``setasign\Fpdi`` and ``setasign/fpdf``. The problem is almost certainly in the first library mentioned. I would ask you to post a corresponding issue on https://github.com/Setasign/FPDI.

Kind regards

**Comment by jumpski** [comment]
I found the issue. I had a empty FDPF class for rector in this spec, so rector can do his magic.
Sorry for the inconvenience and thanks for your help! 

[CLOSED]

**Comment by horstoeko** [comment]
Hi @jumpski,

thank you for your response.

> Sorry for the inconvenience and thanks for your help!

No problem. I'm happy to help. 

Kind regards
