### ISSUE TITLE
[FEATURE] Missing Features in XML Generation Methods

### ISSUE THREAD

**Issue by dinxb** [horstoeko/zugferd#215]
#### 1. Adding `CurrencyID` Attribute to `ChargeAmount` 

In the XML tag `GrossPriceProductTradePrice > ChargeAmount`, I need to include the attribute `currencyID="EUR"`. However, the method `setDocumentPositionGrossPrice()` does not currently allow for this.

####  2. Missing `BasisAmount` Tag in `ApplicableTradeTax`

In the XML tag `SpecifiedLineTradeSettlement` > `ApplicableTradeTax`, I need to include a `BasisAmount` tag. However, the `addDocumentPositionTax()` method also does not support adding this tag. As well the attribute `currencyID="EUR"` is not possible to be added in the `ApplicableTradeTax` > `CalculatedAmount`. 

**Code Example:**
```php
$document->setDocumentPositionGrossPrice($GrossPriceProductTradePrice)
         ->setDocumentPositionQuantity(1, 'C62')
         ->addDocumentPositionTax(
                    categoryCode: $categoryCode,
                    typeCode: 'VAT',
                    rateApplicablePercent: $rateApplicablePercent,
                    calculatedAmount: $calculatedAmount,
                );
```

 **Expected XML Output:** 
 ```
<IncludedSupplyChainTradeLineItem>
    <AssociatedDocumentLineDocument>
        <LineID>1</LineID>
    </AssociatedDocumentLineDocument>
    <SpecifiedLineTradeAgreement>
        <GrossPriceProductTradePrice>
            <ChargeAmount currencyID="EUR">119.00</ChargeAmount>
        </GrossPriceProductTradePrice>
    </SpecifiedLineTradeAgreement>
    <SpecifiedLineTradeDelivery>
        <BilledQuantity unitCode="C62">1</BilledQuantity>
    </SpecifiedLineTradeDelivery>
    <SpecifiedLineTradeSettlement>
        <ApplicableTradeTax>
            <CalculatedAmount currencyID="EUR">19.00</CalculatedAmount>
            <TypeCode>VAT</TypeCode>
            <BasisAmount currencyID="EUR">100.00</BasisAmount>
            <CategoryCode>S</CategoryCode>
            <RateApplicablePercent>19.00</RateApplicablePercent>
        </ApplicableTradeTax>
    </SpecifiedLineTradeSettlement>
</IncludedSupplyChainTradeLineItem>
```
        
        
 I would greatly appreciate it if someone could provide guidance or a solution to these issues.  Thank you :)

**Comment by horstoeko** [comment]
Hello @dinxb,

unfortunately it is obviously no longer necessary to start a conversation with a “Guten Tag” or at least a “Hallo”, so I did it at least once.... ;-)

> Adding CurrencyID Attribute to ChargeAmount

Your request is invalid. GrossPriceProductTradePrice does not have a “currencyID” attribute. See the following from the official documentation:

![image](https://github.com/user-attachments/assets/80eef787-c75a-4ecb-810c-b1f967885cc3)

> Missing BasisAmount tag in ApplicableTradeTax

Your request is invalid. ApplicableTradeTax has no element “BasisAmount” See the following from the official documentation:

![image](https://github.com/user-attachments/assets/3865cd33-36fb-4228-babc-d683a7fed4b6)

Kind regards

**Comment by dinxb** [comment]
You know how we roll around here :) we just get straight to the point! Thanks for enlightening me. Guess I need to read more docs!
