### ISSUE TITLE
[QUESTION] Explainations?

### ISSUE THREAD

**Issue by humpataa** [horstoeko/zugferd#216]
I am having trouble understanding the meaning of several fields.
What is SellerGlobalId? What does 0088 in examples mean?
I have checked Wiki but cannot find details.
Detailed comments of examples would help a lot.
Please advise.

**Comment by horstoeko** [comment]
Hi @humpataa,

> What is SellerGlobalId? 

The Seller's ID identification is a unique identifier assigned to a seller by a global registration organization

> What does 0088 in examples mean

If the identifier is used for the identification scheme, it must be selected from the entries in the list published by the [ISO / IEC 6523 Maintenance Agency](https://github.com/horstoeko/zugferd/blob/master/src/codelists/ZugferdSchemeIdentifiers.php).

I hope I could help.

Kind regards

**Comment by humpataa** [comment]
So I guess it is not really needed.
Minimum examples with extensive comments would be very helpful.
I found it strange that examples seem to be full of overhead and unnecessary things, but obviously missing some ESSENTIAL basic information, such as the buyer's tax registration: this is the KEY reason for all the (german) companies to use electronic invoices, why leave this one out in examples I don't understand.
Anyway - appreciate your work, thank you very much.

**Comment by horstoeko** [comment]
Good evening @humpataa.,

> Minimum examples with extensive comments would be very helpful.

It might be a good idea to participate in the documentation of this project. If you have good ideas on how to make the documentation even better, then I am very open to innovative suggestions. Thank you in advance for your initiative.

Please let me tell you that I am running the project beside my regular job and without sponsorship.

Kind regards.
