### ISSUE TITLE
[QUESTION] Are you aware that documentation is empty since many releases?

### ISSUE THREAD

**Issue by winnyschuster** [horstoeko/zugferd#219]
The Usage section in Readme.md states that documentation is attached to each release, however, since many releases the zip file is empty. Is this intentionally? Also, the formerly attached Builddoc..zip is missing

thank you

**Comment by horstoeko** [comment]
Hi  @winnyschuster,

Thank you very much for the kind advice - unfortunately you can't have your eyes everywhere... :-) Apparently phpDocumentor seems to have a small problem under PHP 8.4. I have reverted the release build to 8.3 and the current release 1.0.99 now has all attachments again.

Thanks again and best regards
