### ISSUE TITLE
[FEATURE] Codelists as enum-classes

### ISSUE THREAD

**Issue by mokraemer** [horstoeko/zugferd#220]
First, thanks for this great project.

At the moment e.g. ZugferdUnitCodes is a list of consts, which is nice in creating invoices, but bad in parsing the units, e.g. zugferdvisualizer. I guess haviong this as an enum could help to prove the value is valid.
I guess for visualisation it still needs a long translation table :(

**Comment by horstoeko** [comment]
Hi @mokraemer,

> First, thanks for this great project.

Thanks for the appreciation, it means a lot!

> At the moment e.g. ZugferdUnitCodes is a list of consts, which is nice in creating invoices, but bad in parsing the units, e.g. zugferdvisualizer. I guess haviong this as an enum could help to prove the value is valid. I guess for visualisation it still needs a long translation table :(

That is certainly a good idea. Unfortunately, I still have the problem that some users of the library still seem to be using PHP 7. You could, however, create a corresponding additional class. What do you think?

Kind regards

**Comment by mokraemer** [comment]
Yeah, I know - always the same with old versions. Even 8.0 is already end of life ([https://www.php.net/supported-versions.php](php versions)). Enums came with 8.1.

Enums is a great concept to make parsing and structures more reliable than usal class consts as ZugferdDocumentReader would return objects instead of strings/int - I would not want to miss them anymore.
But at least I can add the enums and have them optional for parsing and in a later release you can replace the consts with the enums, if you like.

**Comment by mokraemer** [comment]
tbh. I am not familiar with git and github. I am a mercurial/subversion user.
I just know the basics about git - how do I push a changeset here?

**Comment by horstoeko** [comment]
Hi @mokraemer,

> Yeah, I know - always the same with old versions. Even 8.0 is already end of life ([https://www.php.net/supported-versions.php](php versions)). Enums came with 8.1.

I know the PHP enums. I would probably have used them a long time ago, but have had to do without them because of compatibility with older PHP versions...

> But at least I can add the enums and have them optional for parsing and in a later release you can replace the consts with the enums, if you like.

If you could perhaps give me a PR on this later, that would be great. If so, then a corresponding enum counterpart should also be available for all code lists.

Kind regards

**Comment by mokraemer** [comment]
added a pull request.
