### ISSUE TITLE
[QUESTION] [BR-DE-1] Eine Rechnung (INVOICE) muss Angaben zu "PAYMENT INSTRUCTIONS" (BG-16) enthalten.

### ISSUE THREAD

**Issue by humpataa** [horstoeko/zugferd#221]
Beim validieren kommt die o.g. Fehlermeldung.
Ich nehme an, es fehlt die Angabe der Bankverbindung des Verkäufers ... wie setze ich die?

**Comment by horstoeko** [comment]
Hi @humpataa

Could you please adjust your requests so that at least a part of the XML is recognizable? For example, I don't know which payment method you have selected.

Thank you

**Comment by horstoeko** [comment]
Hi @humpataa,

die scheinst vergessen zu haben, die Zahlungsart anzugeben. Ich Schematron-File (Validierungsgrundlage) findet man folgendes:

```xml
<assert test="rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradeSettlementPaymentMeans">
  [BR-DE-1] Eine Rechnung (INVOICE) muss Angaben zu "PAYMENT INSTRUCTIONS" (BG-16) enthalten.
</assert>
```

**Comment by humpataa** [comment]
Ja genau, habe es nun via addDocumentPaymentMean (42 für Überweisung) gesetzt. Das verhindert zunächst die Fehlermeldung, aber ...

... es gibt Rechnungen, die sind schon bezahlt und andere müssen noch bezahlt werden. Wie setze ich das, damit da im Zweifelsfall nicht doppelt bezahlt wird?

Eine Option ist auch Paypal ... gibt es dafür auch einen Code?

**Comment by horstoeko** [comment]
Hi @humpataa,

> ... es gibt Rechnungen, die sind schon bezahlt und andere müssen noch bezahlt werden. Wie setze ich das, damit da im Zweifelsfall nicht doppelt bezahlt wird?

I have not yet had a use case in this regard.
 
> Eine Option ist auch Paypal ... gibt es dafür auch einen Code?

The XRechnung cannot map “PayPal”, “Sofort-Überweisung” etc.

An XRechnung only expects the following 5 values:
- bank card
- credit card
- credit transfer (all online payment types except SEPA)
- debit card
- debit transfer (SEPA direct debit)

This classification of values has its origins in local commerce (cash register systems etc.) In an online store, all payment types are “credit transfer” except SEPA, which is exported as “debit transfer”. Theoretically, you could also specify “credit card” for credit card payments, but the payment method providers such as Paypal unfortunately do not send any information about the exact payment method used. For this reason, Paypal is generally also exported as a credit transfer.

**Comment by horstoeko** [comment]
Hi @humpataa,

> well, known customers can order and pay later. new customers have to pay upfront. that really is not unusual at all. 

I am familiar with this procedure... ;-)

> guess this can be set by TotalPrepaidAmount?

The answer is "Yes" :-)

> does this classification make sense? payments via cash surely are not the majority of B2B payments ...

The sense and nonsense of this can be “argued” in this context. In my personal opinion, some technical errors have been made in the specifications. Unfortunately... :-(

> thank you for the quick help!

I'm always happy to help if I can arrange it. I hope the payment method issue doesn't become your favorite pastime... ;-)

Kind regards
