### ISSUE TITLE
[QUESTION] How to add a Ordernumber / Bestellnummer / BT-13

### ISSUE THREAD

**Issue by alexh-swdev** [horstoeko/zugferd#222]
Maybe I am a bit blind and cannot see the obvious, but can you please guide me how I can add a BT-13 / ordernumber?

**Comment by horstoeko** [comment]
Hi @alexh-swdev,

Depending on which way you look at it, there are.

On document level

* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentsellerorderreferenceddocument
* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentbuyerorderreferenceddocument

On position level

* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentpositionsellerorderreferenceddocument
* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#setdocumentpositionsellerorderreferenceddocument

Best regards
