### ISSUE TITLE
[QUESTION] Reference / Verwendungszweck?

### ISSUE THREAD

**Issue by humpataa** [horstoeko/zugferd#224]
Noch eine Frage zu den Bankdaten, die man zur Bezahlung übergeben kann (passt zum letzten Frage, aber die hast du schon geschlossen).

addDocumentPaymentMean(42, "Überweisung", null, null, null, null, "IBAN123", "Kontoinhaber", null, "BIC123")

Wie übergebe ich das Feld, das als "Verwendungszweck" angezeigt wird?

**Comment by humpataa** [comment]
Hat sich erledigt, habe es mit addDocumentPaymentMeanToCreditTransfer gelöst.

**Comment by horstoeko** [comment]
Hi @humpataa,

that's absolutely correct:

![image](https://github.com/user-attachments/assets/84df5831-486b-47dd-90cf-b4f26ca3df7d)

It was described in the docs to:  https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#adddocumentpaymentmeantocredittransfer

Kind regards
