### ISSUE TITLE
[QUESTION] looking for PartyTaxScheme

### ISSUE THREAD

**Issue by humpataa** [horstoeko/zugferd#226]
Sorry to bother again. I have seen in other valid example XML that the proper way to set the buyer's tax info is to use this:

```
<cac:AccountingCustomerParty>
    <cac:Party>
...
      <cac:PartyTaxScheme>
        <cbc:CompanyID>USTID</cbc:CompanyID>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:PartyTaxScheme>
      <cac:PartyLegalEntity>
        <cbc:RegistrationName>dfgsdfgsdfg</cbc:RegistrationName>
      </cac:PartyLegalEntity>

    </cac:Party>
</cac:AccountingCustomerParty>
```

Yet, I cannot find the function to set this – please advise.

**Comment by horstoeko** [comment]
Hi,

* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#adddocumentsellertaxregistration
* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#adddocumentbuyertaxregistration

There are two shortcut methods for the first method mentioned:

* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#adddocumentsellertaxregistration
* https://github.com/horstoeko/zugferd/wiki/Class-ZugferdDocumentBuilder#adddocumentsellervatregistrationnumber

For the seconds there are currently no shortcut-methods
