### ISSUE TITLE
PHP 8.0 and 8.1 support?

### ISSUE THREAD

**Issue by jacobsenj** [horstoeko/zugferd#3]
Will the package work with PHP 8.0 and 8.1 or why is it limited to 7.3.0 in the composer.json?

**Comment by horstoeko** [comment]
Hi @jacobsenj,

thanks for your issue. I have not yet had time to fully test the library with PHP8. But I want to do that as soon as possible. If you like, you can also fork the project and try it yourself, if there are problems with PHP8. Also I would be happy about a pull request after a successful test from your side.

**Comment by horstoeko** [comment]
Hi @jacobsenj,

I have made a new release. Version [1.0.9,](https://github.com/horstoeko/zugferd/releases/tag/v1.0.9
) now also supports PHP 8.0 and 8.1.
