### ISSUE TITLE
Payment Usage BT-83

### ISSUE THREAD

**Issue by lopePrime** [horstoeko/zugferd#30]
**Your question**
Hello. I cann't find the function to call to fill the payment usage BT-83 for SEPA credit transfer (58).
Which one do i have to use?

**Comment by horstoeko** [comment]
Hi @lopePrime 

i think `ZugferdDocumentBuilder::setDocumentGeneralPaymentInformation` is the method you are looking for... Give it a try... :-) Please give me feedback if this answers your question. If not, we'll have to delve deeper into the issue.

Kind regards

**Comment by lopePrime** [comment]
Sure, of course! I could have guessed from the description :) It works, thank you very much.
A really nice project!

**Comment by horstoeko** [comment]
> Sure, of course! I could have guessed from the description :) It works, thank you very much. A really nice project!

Nice. Thank you for your response...

Kind regards
