### ISSUE TITLE
Generating electronic quotes

### ISSUE THREAD

**Issue by LarsK1** [horstoeko/zugferd#34]
**Your question**
Hi,
we're looking for generating electronic quotes. Which document type should we use to accomplish this? We didn't find any type suitable.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by horstoeko** [comment]
Hi @LarsK1 ,

As far as I know, ZUGFeRD/Factur-X is not intended for sending quotes. The official documentation states this:

> We recommend the following Codes for ZUGFeRD of profile BASIC or higher:
> * 380 : Commercial invoice
> * 381 : Credit notification
> * 384 : Invoice correction
> * 389 : Self billed invoice - credit note within a credit note process (an invoice made out by the Payment Undertaker instead of by the seller).
> * 261 : Self billed credit note - a document which indicates that the customer is claiming credit in a self billing environment
> * 386 : Prepayment – An invoice which requires a prepayment for products. The respective amounts will be deducted in the final bill.
> * 326: Partial billing
>
> For profiles BASIC WL and MINIMUM, the following code must be used exclusively:
> * 751 : Posting aid – NO invoice

I myself cannot find a document type for quote in the code list (UNTDID 1001) either.

Best regards...

**Comment by LarsK1** [comment]
Hi @horstoeko ,
thanks, that was, what I thougth it would be. 

Thank you for your quick help anyways!

**Comment by horstoeko** [comment]
Hi  @LarsK1,

you can have a look in the codelist [UNTDID1001](https://github.com/horstoeko/zugferd/wiki/Codelists#untdid-1001). There is a document type **310**. Maybe this one could help...

Best regards
