### ISSUE TITLE
WriteEInvoicePDFAndXML and "existingprintlayout.pdf"

### ISSUE THREAD

**Issue by AvengerD** [horstoeko/zugferd#35]
I am just starting to implement E-Invoices for our PHP-based shop-system, and a ran across this great class-library.

So far, I think I understood the concept quite well, however there is one question I found no answer to so far.

It concerns "WriteEInvoicePDFAndXML" and the "existingprintlayout.pdf" used in it.

As far as I understood, you can create bot the PDF- and XML-part of an E-Invoice, is that correct?

I guess "existingprintlayout.pdf" is some sort of template file for the PDF invoice-format, but I can't find this file in the installed software installed with composer.

So, may question is: how is this supposed to work?

Is there an "existingprintlayout.pdf"-file, and how can I get hold of it?

Is there a description of how these PDF-templates should look like?

Hope you can enlighten me somehow.

And thanks for this tremendous work!

**Comment by horstoeko** [comment]
Hi @AvengerD,

thank you for you question.

> I guess "existingprintlayout.pdf" is some sort of template file for the PDF invoice-format, but I can't find this file in the installed software installed with composer.

_existingprintlayout.pdf_ is just one example. You must of course generate an invoice document with all the necessary information in some way (from whatever source) as a PDF. My library does not do that. It merely ensures that you

* create a compliant XML and
* a compliant PDF with an embedded XML 

can be generated. Please have another look in the examples folder of the library or in the [Wiki ](https://github.com/horstoeko/zugferd/wiki)of this project. One good example is [this](https://github.com/horstoeko/zugferd/blob/master/examples/En16931SimpleWithPdf.php). I think that I have documented everything quite well.

If you have any further questions, I will of course be happy to answer them.

**Comment by AvengerD** [comment]
Hi, horstoeko,

 

thx for your quick answer.

So your software takes an existing PDF-Invoice, creates the XML for the invoice and then attaches the XML to the PDF file…

Got it!

<< I think that I have documented everything quite well.>>

Yes, indeed!

 

Von: horstoeko ***@***.*** 
Gesendet: Dienstag, 2. April 2024 08:07
An: horstoeko/zugferd
Cc: Avenger; Mention
Betreff: Re: [horstoeko/zugferd] WriteEInvoicePDFAndXML and "existingprintlayout.pdf" (Issue #35)

 

Hi  <https://github.com/AvengerD> @AvengerD,

thank you for you question.

I guess "existingprintlayout.pdf" is some sort of template file for the PDF invoice-format, but I can't find this file in the installed software installed with composer.

existingprintlayout.pdf is just one example. You must of course generate an invoice document with all the necessary information in some way (from whatever source) as a PDF. My library does not do that. It merely ensures that you

*	create a compliant XML and
*	a compliant PDF with an embedded XML

can be generated. Please have another look in the examples folder of the library or in the  <https://github.com/horstoeko/zugferd/wiki> Wiki of this project. One good example is  <https://github.com/horstoeko/zugferd/blob/master/examples/En16931SimpleWithPdf.php> this. I think that I have documented everything quite well.

If you have any further questions, I will of course be happy to answer them.
