### ISSUE TITLE
[FEATURE] Symfony 7 support

### ISSUE THREAD

**Issue by DubbleClick** [horstoeko/zugferd#45]
**Describe the feature**
This projects composer.json currently supports symfony packages with ^5|^6. Current symfony version is 7.0, therefore it's not possible to use this package in up-to-date Symfony projects.

**Comment by horstoeko** [comment]
Hi @DubbleClick,

Thanks for the issue. Would you perhaps make a pull request? I'm very busy at the moment and can't promise that I'll be able to do it this week. I can do a pull request quickly from my cell phone... :-).

Regards

**Comment by DubbleClick** [comment]
@horstoeko Already created in #46  :)

**Comment by horstoeko** [comment]
Hi @DubbleClick,

my mistake... ;-) I have merged the pull request #46

Best regards
