### ISSUE TITLE
ubl support

### ISSUE THREAD

**Issue by chris-sx** [horstoeko/zugferd#48]
It would be nice if ubl (i only found this https://github.com/horstoeko/ubl) could be integrated or if there is a idea to use it with zugferd or zugferdvisualizer.

Do you have pans with that?

Thanks 
Chris

**Comment by horstoeko** [comment]
Hi @chris-sx,

Nothing is planned in this regard at the moment. The structure and layout are so different that I would first have to develop an idea of how I could integrate UBL into this library. But to be honest, I was expecting this question at some point.... :-)

Kind regards

**Comment by chris-sx** [comment]
Hi,

 

das wäre wirklich toll, weil laut Gesetz müssen diese ja auch unterstützt werden und ohne ist das zugferd ja nicht ausreichen und ich müsste noch mal weitergucken. Ich würde das auch gerne irgendwie unterstützen.

 

Ich habe nicht verstanden: horstoeko/ubl kann doch das ubl-xml lesen oder? Was fehlt denn dann noch?

 

 

Viele Grüße

Christian Schröder

 

 

 

Von: horstoeko ***@***.***> 
Gesendet: Mittwoch, 15. Mai 2024 15:44
An: horstoeko/zugferd ***@***.***>
Cc: chris-sx ***@***.***>; Mention ***@***.***>
Betreff: Re: [horstoeko/zugferd] ubl support (Issue #48)

 

Hi @chris-sx <https://github.com/chris-sx> ,

Nothing is planned in this regard at the moment. The structure and layout are so different that I would first have to develop an idea of how I could integrate UBL into this library. But to be honest, I was expecting this question at some point.... :-)

Kind regards

**Comment by chris-sx** [comment]
Hallo,

 

ich nochmal: 

wenn ein ubl nicht erkannt werden kann, kommt aber derzeit kein Fehler, das script stürzt einfach ab. Da wäre es irgendwie schön, wenn man das abfängt und ggf. auf einem andern weg weiterarbeitet?! Ist das viel Aufwand?

 

Viele Grüße

Christian Schröder

 

 

Von: horstoeko ***@***.***> 
Gesendet: Mittwoch, 15. Mai 2024 15:44
An: horstoeko/zugferd ***@***.***>
Cc: chris-sx ***@***.***>; Mention ***@***.***>
Betreff: Re: [horstoeko/zugferd] ubl support (Issue #48)

 

Hi @chris-sx <https://github.com/chris-sx> ,

Nothing is planned in this regard at the moment. The structure and layout are so different that I would first have to develop an idea of how I could integrate UBL into this library. But to be honest, I was expecting this question at some point.... :-)

Kind regards

**Comment by horstoeko** [comment]
Hi @chris-sx , 

> Hallo, ich nochmal: wenn ein ubl nicht erkannt werden kann, kommt aber derzeit kein Fehler, das script stürzt einfach ab. Da wäre es irgendwie schön, wenn man das abfängt und ggf. auf einem andern weg weiterarbeitet?! Ist das viel Aufwand?

Ich würde das prüfen. Könntest Du mir liebenswürdigerweise eine oder mehrere Dateien in UBL-Syntax zur Verfügung stellen?

**Comment by chris-sx** [comment]
Hi,

 

vielen Dank.

 

Es gibt hier einige: 

https://www.erechnung.gv.at/erb/downloads?tab=tec <https://www.erechnung.gv.at/erb/downloads?tab=tec&tab=tec> &tab=tec

 

und anbei habe ich einige Muster erhalten  von https://xrechnungsgenerator.nortal.com <https://xrechnungsgenerator.nortal.com/> 

 

 

Viele Grüße

Christian Schröder

 

 

 

Von: horstoeko ***@***.***> 
Gesendet: Donnerstag, 16. Mai 2024 05:47
An: horstoeko/zugferd ***@***.***>
Cc: chris-sx ***@***.***>; Mention ***@***.***>
Betreff: Re: [horstoeko/zugferd] ubl support (Issue #48)

 

Closed #48 <https://github.com/horstoeko/zugferd/issues/48>  as completed.

**Comment by chris-sx** [comment]
Well, the whole UBL hasn't been maintained for a long time and I can't find any examples for 2.1, Austria is something else again  (eb?)

Maybe it's outdated.

**Comment by chris-sx** [comment]
But an good error, if the format is not readabel would be very nice.

**Comment by horstoeko** [comment]
Hi,

in the upcoming release i have more granular exception classes implemented - for several situations. In your case the following is a possible solution:

```php
try {
    $document = ZugferdDocumentPdfReader::readAndGuessFromFile(dirname(__FILE__) . "/invoice.xml");
} catch (ZugferdUnknownProfileException $e) {
    // Whatever you want to do in this case... :-)
}
```

I hope this helps

Best regards
