### ISSUE TITLE
[FEATURE] Add Creditor ID to addDocumentPaymentMeanToDirectDebit()?

### ISSUE THREAD

**Issue by danielmarschall** [horstoeko/zugferd#53]
The following code:
`$document->addDocumentPaymentMeanToDirectDebit('DE02100500000054540402');`

Produces (using XRechnung3 Profile):
```
      <ram:SpecifiedTradeSettlementPaymentMeans>
        <ram:TypeCode>59</ram:TypeCode>
        <ram:PayerPartyDebtorFinancialAccount>
          <ram:IBANID>DE02100500000054540402</ram:IBANID>
        </ram:PayerPartyDebtorFinancialAccount>
      </ram:SpecifiedTradeSettlementPaymentMeans>
```

The validator does reject the document, because Credit Identifier (Gläubiger ID) is missing:

```
val-sch.2.1	BR-DE-30	error	[BR-DE-30] Wenn "DIRECT DEBIT" BG-19 vorhanden ist, dann muss "Bank assigned creditor identifier" BT-90 übermittelt werden.
Pfad: /rsm:CrossIndustryInvoice
```

According to [this article](https://blog.seeburger.com/de/xrechnung-2-3-1-gueltig-ab-dem-01-08-2023/) , these are the changes for XRechnung 2.3.1

- BR-DE-29: Das Element „Mandate reference identifier“ (BT-89) muss übermittelt werden, wenn die Gruppe DIRECT DEBIT“ (BG-19) übermittelt wird.
- BR-DE-30: Das Element „Bank assigned creditor identifier“ (BT-90) muss übermittelt werden, wenn die Gruppe „DIRECT DEBIT“ (BG-19) übermittelt wird.
- BR-DE-31: Das Element „Debited account identifier“ (BT-91) muss übermittelt werden, wenn die Gruppe „DIRECT DEBIT“ (BG-19) übermittelt wird.

**Comment by danielmarschall** [comment]
The missing information is:

```
  <ram:ApplicableHeaderTradeSettlement>
    <ram:CreditorReferenceID>xxx</ram:CreditorReferenceID>
  <ram:ApplicableHeaderTradeSettlement>

```

Looking at the code, it can be set using `setDocumentGeneralPaymentInformation`.

Since the Creditor Identifier is a mandatory information to direct debit, wouldn't it be better to (additionally) include it as paramter to addDocumentPaymentMeanToDirectDebit() ?


```
    public function addDocumentPaymentMeanToDirectDebit(string $buyerIban, string $creditorReferenceID): ZugferdDocumentBuilder
    {
        $paymentMeans = $this->getObjectHelper()->getTradeSettlementPaymentMeansType("59");
        $buyerfinancialaccount = $this->getObjectHelper()->getDebtorFinancialAccountType($buyerIban);

        $this->getObjectHelper()->tryCall($paymentMeans, "setPayerPartyDebtorFinancialAccount", $buyerfinancialaccount);

        $this->getObjectHelper()->tryCallAll($this->headerTradeSettlement, ["addToSpecifiedTradeSettlementPaymentMeans", "setSpecifiedTradeSettlementPaymentMeans"], $paymentMeans);


        // ADD THIS?
        $this->getObjectHelper()->tryCall($this->headerTradeSettlement, "setCreditorReferenceID", $this->getObjectHelper()->getIdType($creditorReferenceID));


        return $this;
    }


```

**Comment by horstoeko** [comment]
Hi @danielmarschall,

> Since the Creditor Identifier is a mandatory information to direct debit, wouldn't it be better to (additionally) include it as paramter to addDocumentPaymentMeanToDirectDebit() ?

Yes, this is a good idea. I would include that as an additional parameter. But please give me time, I have a normal job... :-) You are of course free to set a pull request.

Best regareds...
