### ISSUE TITLE
Why DateTime instead of DateTimeInterface

### ISSUE THREAD

**Issue by Schrank** [horstoeko/zugferd#58]
Many methods, e.g.

    \horstoeko\zugferd\ZugferdDocumentBuilder::setDocumentInformation

have an explicit type check for DateTime, while it could (and should?) be DateTimeInterface. That makes it easier to use DateTimeImmuteable as I do.

Is there a reason to be explicit about it?

**Comment by horstoeko** [comment]
Hi @Schrank,

Unfortunately, I have no memory of why I implemented this at the time. You are also welcome to make a PR for this.

Best regards

**Comment by Schrank** [comment]
Thanks! ☺️
