### ISSUE TITLE
[FEATURE] Detailed Input Value References in DocumentBuilder

### ISSUE THREAD

**Issue by OLLIVAULT** [horstoeko/zugferd#65]
**Describe the feature**
Would it be possible for the DocumentBuilder to include the corresponding BT-XX for each input value? Indeed, it is not always easy to find them. Additionally, could you indicate for which profile it is called and if this value is required for the profile(s) in question ?

**Sample Code**
```php
/**
     * Set grouping of business process information
     *
     * @param string $id // BT-23 (all-profile -> require = true)
     * Identifies the context of a business process where the transaction is taking place, thus allowing the buyer to
     * process the invoice in an appropriate manner.
     * __Note__: These data make it possible to define the purpose of the settlement (invoice of the authorised person,
     * contractual partner, subcontractor, settlement document for a building contract etc.).
     * @return ZugferdDocumentBuilder
     */
    public function setDocumentBusinessProcess(string $id): ZugferdDocumentBuilder
    {
        if ($this->getObjectHelper()->isNullOrEmpty($id)) {
            return $this;
        }

        $busProcessCtxParameter = $this->getObjectHelper()->createClassInstance('ram\DocumentContextParameterType');
        $this->getObjectHelper()->tryCall($busProcessCtxParameter, 'setID', $this->getObjectHelper()->getIdType($id));
        $this->getObjectHelper()->tryCall($this->getInvoiceObject()->getExchangedDocumentContext(), 'setBusinessProcessSpecifiedDocumentContextParameter', $busProcessCtxParameter);

        return $this;
    }
```

**Comment by horstoeko** [comment]
Hi @OLLIVAULT,

Thanks first of all for the issue. This is a lot of work and I can't promise that it can be done in the next few days/weeks. Basically, however, it doesn't matter which profile the function/method applies to. The approach of the library is that you don't have to worry about the profiles (and the methods to be called). However, the idea with the BT-* is good in that you can find the required methods (and therefore also the parameters) more quickly. As I said, a lot of work. If you want to support me, I would be very happy. I'm very busy at work at the moment and don't know when I'll find the time.

Best regards....

**Comment by OLLIVAULT** [comment]
> dans

Hi horstoeko,

First of all, I want to thank you immensely for all the work you've done. You've saved me an enormous amount of time, and I would be happy to help you out. Just give me an example of how you'd like me to set it up.

**Comment by horstoeko** [comment]
Hi @OLLIVAULT,

Many, many thanks for the praise and appreciation. I really enjoy reading (and hearing) that.

I think we should follow the example below:

```php
/**
 * Set grouping of business process information
 *
 * @param string $id
 * __BT23, All Profiles__: Identifies the context of a business process where the transaction is taking place, thus allowing the buyer to
 * process the invoice in an appropriate manner.
 * __Note__: These data make it possible to define the purpose of the settlement (invoice of the authorised person,
 * contractual partner, subcontractor, settlement document for a building contract etc.).
 * @return ZugferdDocumentBuilder
 */
public function setDocumentBusinessProcess(string $id): ZugferdDocumentBuilder
{
    if ($this->getObjectHelper()->isNullOrEmpty($id)) {
        return $this;
    }

    $busProcessCtxParameter = $this->getObjectHelper()->createClassInstance('ram\DocumentContextParameterType');
    $this->getObjectHelper()->tryCall($busProcessCtxParameter, 'setID', $this->getObjectHelper()->getIdType($id));
    $this->getObjectHelper()->tryCall($this->getInvoiceObject()->getExchangedDocumentContext(), 'setBusinessProcessSpecifiedDocumentContextParameter', $busProcessCtxParameter);

    return $this;
}
```

So: The BT rule at the very beginning, then a reference to the profiles separated by a comma.

Is that sufficient from your point of view?

Best regards...
