### ISSUE TITLE
[DOC] Documentation error at ...TaxRegistration-functions

### ISSUE THREAD

**Issue by cnd-jmu** [horstoeko/zugferd#72]
There are multiple functions to add tax registration of various participants which share parameters, code and documentation. 
I guess the order of the two parameters was once reversed and thereby some documentation errors emerged. 
I stumbled upon it while comparing the ZugferdQuickDescriptor example with the corresponding documented source code to be able to understand all the parameters. 

To find all occurences use this search: 
https://github.com/search?q=repo%3Ahorstoeko%2Fzugferd+path%3A%2F%5Esrc%5C%2F%2F+TaxRegistration%28&type=code

Some examples:

https://github.com/horstoeko/zugferd/blob/f0c6840546bf773306d6864bfda761eef4c4a0e2/src/ZugferdDocumentBuilder.php#L483

Currently the documentation of `$taxregtype` and `$taxregid` is like this:
```
     * @param  string|null $taxregtype Type of tax number of the seller
     * @param  string|null $taxregid   Tax number of the seller or sales tax identification number of the (FC = Tax number, VA = Sales tax number)
     * @return ZugferdDocumentBuilder
     */
    public function addDocumentSellerTaxRegistration(?string $taxregtype = null, ?string $taxregid = null): ZugferdDocumentBuilder
```
It should be like this:
```
     * @param  string|null $taxregtype Type of tax number of the seller (FC = Tax number, VA = Sales tax identification number)
     * @param  string|null $taxregid   Tax number of the seller or sales tax identification number of the seller
     * @return ZugferdDocumentBuilder
     */
    public function addDocumentSellerTaxRegistration(?string $taxregtype = null, ?string $taxregid = null): ZugferdDocumentBuilder
```

https://github.com/horstoeko/zugferd/blob/f0c6840546bf773306d6864bfda761eef4c4a0e2/src/quick/ZugferdQuickDescriptor.php#L453

Currently the documentation and parameter naming of `$taxregtype` and `$taxregid` is like this:
```
     * @param  string $no
     * Tax number of the buyers
     * @param  string $schemeID
     * Tax number of the buyers or sales tax identification number of the (FC = Tax number, VA = Sales tax number)
     * @return ZugferdQuickDescriptor
     */
    public function doAddBuyerTaxRegistration(string $no, string $schemeID): ZugferdQuickDescriptor
    {
        $this->addDocumentBuyerTaxRegistration($no, $schemeID);
```
It should be like this:
```
     * @param  string|null $taxregtype Type of tax number of the seller (FC = Tax number, VA = Sales tax identification number)
     * @param  string|null $taxregid   Tax number of the seller or sales tax identification number of the seller
     * @return ZugferdQuickDescriptor
     */
    public function doAddBuyerTaxRegistration(?string $taxregtype = null, ?string $taxregid = null): ZugferdQuickDescriptor
    {
        $this->addDocumentBuyerTaxRegistration($taxregtype, $taxregid);
```

**Comment by horstoeko** [comment]
Hi @cnd-jmu,

Feel free to set me a PR.
