### ISSUE TITLE
[BUG] ZugferdSettings::setUnitAmountDecimals() only works for the first item

### ISSUE THREAD

**Issue by dennisnissle** [horstoeko/zugferd#73]
**Describe the bug**
The newly introduced setter to set amount decimals for a specific schema does only work for the first item added to the document. The next item will have a different node path, e.g.: 

### First item
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedLineTradeAgreement/ram:GrossPriceProductTradePrice/ram:ChargeAmount

### Second item
/rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem[2]/ram:SpecifiedLineTradeAgreement/ram:GrossPriceProductTradePrice/ram:ChargeAmount

Mind the [2] within IncludedSupplyChainTradeLineItem. This way calling ZugferdSettings::setUnitAmountDecimals() will only affect the first item as the schema within the setter is explicitly set to /rsm:CrossIndustryInvoice/rsm:SupplyChainTradeTransaction/ram:IncludedSupplyChainTradeLineItem/ram:SpecifiedLineTradeAgreement/ram:GrossPriceProductTradePrice/ram:ChargeAmount

**To Reproduce**
Use:

```php
ZugferdSettings::setUnitAmountDecimals( 5 );
$document = ZugferdDocumentBuilder::CreateNew( ZugferdProfiles::PROFILE_XRECHNUNG_2_3 );

for ( $i = 1; $i <= 10; $i++ ) {
    $document->addNewPosition( $i );

    $document->setDocumentPositionGrossPrice( 10.22552 );
    $document->setDocumentPositionNetPrice( 10.22552 );
    $document->setDocumentPositionLineSummation( 10.23 );
}

echo $document->getContent();
exit();
```

See how prices starting with the second item will be rounded to 2 decimals in the output xml file.

**Expected behavior**
Should work for all the items added.

Best,
Dennis

**Comment by danielmarschall** [comment]
Good catch! I suggest to remove all [\d+] from the path using regex. @horstoeko what do you think?

**Comment by horstoeko** [comment]
Hi @danielmarschall 

just try it. Test it locally and make a PR

**Comment by danielmarschall** [comment]
Fixed :-)

PHPUnit tests passed. And example above now works.

I am very happy that `setUnitAmountDecimals()` exists. @dennisnissle has the same problem like me with the rounding problems when being forced from converting from gross to net.

**Comment by horstoeko** [comment]
Hi @danielmarschall,

Nice! Many thanks....

> I am very happy that setUnitAmountDecimals() exists

Sure :-)

Best regards
