### ISSUE TITLE
[FEATURE]Add the PHP requirement to the Readme

### ISSUE THREAD

**Issue by chrillek** [horstoeko/zugferd#79]
**Describe the feature**
It should be made clear at the beginning of the README that PHP is a requirement for this software. Right now, we'll have dive into the repository to see that.

**Comment by horstoeko** [comment]
Hi @chrillek,

thank you for you Issue. Although I think that in the installation point the reference to “composer” already indicates that it is a PHP library, I will gladly comply with the request. Incidentally, there is also a note at the top right of the repository start page that it could be a PHP application:

![image](https://github.com/horstoeko/zugferd/assets/2326713/5c2231b1-b1d8-4114-a656-c69ff5e334d9)

and a little further down on the right...

![image](https://github.com/horstoeko/zugferd/assets/2326713/eec52bce-ff23-4ea2-a992-d015639ac046)
