### ISSUE TITLE
Example how to use getDocumentAdditionalReferencedDocument

### ISSUE THREAD

**Issue by chris-sx** [horstoeko/zugferd#88]
I try to make anything with getDocumentAdditionalReferencedDocument, but Inever get any details.
Smething like that?

$Attachments = $document->getDocumentAdditionalReferencedDocuments($additionalrefdocs);
foreach ($additionalrefdocs as $key => $value) {
       $issuerassignedid = $value[IssuerAssignedID];
       $test_Attachment = $document->firstDocumentAdditionalReferencedDocument($value[IssuerAssignedID]);
       print_r($test_Attachment);

OR MAYBE 
     $test_Attachment = $document->getDocumentAdditionalReferencedDocument($issuerassignedid);
}

How can I acces the details in the example xml enlosed?

Thanks
Chris
[XRECHNUNG_Elektron.xml.txt](https://github.com/user-attachments/files/15791533/XRECHNUNG_Elektron.xml.txt)

**Comment by horstoeko** [comment]
Hi @chris-sx ,

I'm currently on a business trip to Belgium. I'm afraid I'll have to put you off until the end of the week with an answer

**Comment by horstoeko** [comment]
HI @chris-sx,

I quickly added another example this morning... See [/examples/En16931AdditionalRefDocument.php](https://github.com/horstoeko/zugferd/blob/master/examples/En16931AdditionalRefDocument.php). I hope this helps.

Kind regards

**Comment by chris-sx** [comment]
No need to hurry! 
I always get a value 1 in $binarydatafilename
Where should that tmp directory be, it must be chmod 755 I guess?

**Comment by horstoeko** [comment]
Hi @chris-sx 

Maybe you can send me your Code?

Kind regards...

**Comment by chris-sx** [comment]
Thanks for the quick response. Everything ok, I found it, I had the tmp on root where I do not have rights. 
  
Rgards
