### ISSUE TITLE
Multiple Deprecation Warnings in 1.0.54

### ISSUE THREAD

**Issue by tkempf** [horstoeko/zugferd#89]
with php 8 you get multiple deprecation warnings when running the Code. Would be nice if you could change the parameter order and/or parameter defaults.

`Deprecated: Optional parameter $typeCode declared before required parameter $calculatedAmount is implicitly treated as a required parameter in /var/www/html/prdevel/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php on line 2346

Deprecated: Optional parameter $taxCategoryCode declared before required parameter $rateApplicablePercent is implicitly treated as a required parameter in /var/www/html/prdevel/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php on line 2478

Deprecated: Optional parameter $typeCode declared before required parameter $rateApplicablePercent is implicitly treated as a required parameter in /var/www/html/prdevel/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php on line 3433`

**Comment by horstoeko** [comment]
Hi @tkempf ,

I will have a look on that as soon as I am back from my business trip.


Kind regards
