### ISSUE TITLE
[ENHANCEMENT] Issue with Adding Multiple BT-29 Using ->setDocumentSeller() in BASIC Profile

### ISSUE THREAD

**Issue by OLLIVAULT** [horstoeko/zugferd#90]
Hi @horstoeko, 
**Describe the bug**

In the BASIC profile, I can't add multiple BT-29 with ->setDocumentSeller().
Only the last sellertradeparty taken into account is correct.
```xml
<ram:SellerTradeParty>
        <ram:ID>910</ram:ID>
        <ram:Name>Lieferant GmbH</ram:Name>
        <ram:PostalTradeAddress>
          <ram:CountryID>FR</ram:CountryID>
        </ram:PostalTradeAddress>
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">6</ram:ID>
        </ram:SpecifiedTaxRegistration>
</ram:SellerTradeParty>
```

**To Reproduce**
```php 
$document
                ->setDocumentSeller("Lieferant GmbH", "549910")
                ->setDocumentSeller("Lieferant GmbH", "910");
```

**Comment by horstoeko** [comment]
Hi @OLLIVAULT ,

The cardinallity of BR-29 is 1:1 i think. Fir me this is not a Bug.

**Comment by OLLIVAULT** [comment]
![Capture d’écran 2024-06-14 à 08 49 34](https://github.com/horstoeko/zugferd/assets/169679285/80424c5e-ce9f-4355-ab6d-d36d6cf38a3f)

**Comment by horstoeko** [comment]
Hi @OLLIVAULT ,

I will look when back from my  Business trip. At the Moment this is not implemented. Is this a big problem? 

Bye.

**Comment by OLLIVAULT** [comment]
It is not present, and that's a big problem, No, but it's a problem.
Thank you again.
