### ISSUE TITLE
Deprecated: Optional parameter $typeCode declared before required parameter

### ISSUE THREAD

**Issue by JuergenGuggemos** [horstoeko/zugferd#98]
**Describe the bug**
Deprecated: Optional parameter $typeCode declared before required parameter $calculatedAmount is implicitly treated as a required parameter in /home/Juergen/projects/shop/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php:2346

Deprecated: Optional parameter $taxCategoryCode declared before required parameter $rateApplicablePercent is implicitly treated as a required parameter in /home/Juergen/projects/shop/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php:2478

Deprecated: Optional parameter $typeCode declared before required parameter $rateApplicablePercent is implicitly treated as a required parameter in /home/Juergen/projects/shop/vendor/horstoeko/zugferd/src/ZugferdDocumentBuilder.php:3433

**To Reproduce**
Install the package via composer and run the sample Code.

**Expected behavior**
The bug description is shown.

**Sample Code
Run the sample Code:
https://github.com/horstoeko/zugferd/tree/8ad5b36d2cb1d69c118c78309d50deb1da7466c7?tab=readme-ov-file#writing-a-xml-file

**Additional information:**
 - OS: [Linux]
 - PHP-Version [PHP8.2]

**Comment by horstoeko** [comment]
Hi @JuergenGuggemos,

thank you for contributing the issue. Are you sure, that the linenumbers in you issue description are correct? Please rebase your feature branch or pull latest version (git pull).

Kind regards

**Comment by JuergenGuggemos** [comment]
Yes, the problem was solved with the update.
