### ISSUE TITLE
How to use addDocumentPositionAdditionalReferencedDocument?

### ISSUE THREAD

**Issue by chris-sx** [horstoeko/zugferd#99]
I found addDocumentPositionAdditionalReferencedDocument which might be very usefull for details on a position but I amnot able to use it, it alway is ignored:

$attachdoc1 = "./tmp/Test-PDF.pdf";
$issuerassignedid1= "Dok zu Pos $linexNumber";
$document->addDocumentPositionAdditionalReferencedDocument($issuerassignedid1, "916", $uriid, $lineNumber, "file", 'CAW', $issueddate = null, $attachdoc1); 

What am I missing?

Thanks
Chris

**Comment by horstoeko** [comment]
Hi @chris-sx,

can you please tell me which profile you are using?

Kind regards

**Comment by chris-sx** [comment]
Ok, that doesn't make sense to use. Extended gives to much other issues.
I stay with PROFILE_XRECHNUNG_3, hope that is valid for a few years.

Many many thanks for your great and always quick support.
